# Copyright (c) 2023-2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: ubuntu/24.04

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  - fish
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev

tasks:
  - setup: |
      sudo pip install -U pip setuptools wheel poetry nox
      cd aipress24
      poetry install

  - lint: |
      cd aipress24
      poetry run make lint

  - test: |
      cd aipress24
      poetry run make test

  - nox: |
      cd aipress24
      poetry run nox

#triggers:
#  - action: email
#    condition: failure
#    to: builds@fermigier.com
