# Copyright (c) 2023-2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: ubuntu/24.04

packages:
    # Build tools
    - software-properties-common
    - build-essential
    - make
    - gcc
    - g++
    - fish
    # Python
    - python3-dev
    - python3-pip
    - python3-wheel
    # Libraries for databases
    - libsqlite3-dev
    - libpq-dev
    # Other libraries
    - libffi-dev
    - libbz2-dev

tasks:
    - setup: |
          sudo pip install --break-system-packages -U uv nox
          cd aipress24
          uv sync --frozen

    - lint: |
          cd aipress24
          uv run make lint

    - test: |
          cd aipress24
          uv run make test-sqlite
          uv run pytest tests --typeguard-packages=app tests
          # TODO: test with postgresql

    - nox-test: |
          cd aipress24
          uv run nox -e test-3.12
          # TODO: postgres

    - nox-lint: |
          cd aipress24
          uv run nox -e lint

triggers:
    - action: email
      condition: failure
      to: builds@fermigier.com
