# Copyright (c) 2023-2024, Abilian SAS
#
# SPDX-License-Identifier: BSD-3-Clause

image: ubuntu/24.04

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  - fish
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev

tasks:
  - setup: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source ~/.local/bin/env
      cd aipress24
      uv sync
      uvx poetry install

  - lint: |
      source ~/.local/bin/env
      cd aipress24
      uv run make lint

  - test: |
      source ~/.local/bin/env
      cd aipress24
      uv run make test-sqlite
      # TODO: test with postgresql

  - nox-test: |
      source ~/.local/bin/env
      cd aipress24
      uv run nox -e test-3.12
      # TODO: postgres

  - nox-lint: |
      source ~/.local/bin/env
      cd aipress24
      uv run nox -e lint

triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
