["Éditoriales"]
1 = "Définir la ligne éditoriale"
2 = "Diriger une rubrique"
3 = "Présenter un journal Radio"
4 = "Présenter un journal télévisé"
5 = "Rédiger des articles"
6 = "Rewriter"
7 = "Manier les données numériques"
8 = "Photographier"
9 = "Filmer"
10 = "Mise en page"
11 = "Graphisme"
12 = "Illustration"
13 = "Vidéo"
14 = "Conception sonore"
15 = "Iconographie"
16 = "Data-visualisation"

["Communication"]
1 = "Définir la stratégie de communication"
2 = "Communication de crise"
3 = "Animer une communauté"
4 = "Influencer des communautés"
5 = "Lobbying"
6 = "Organiser d'événements"
7 = "Animer un club"
8 = "Animer une table ronde"
9 = "Media Coaching"

["Operationnelles"]
1 = "Finances"
2 = "Comptabilité"
3 = "Juridique"
4 = "Marketing"
5 = "Communication institutionnelle"
6 = "Relations de Presse"
7 = "Ventes"
8 = "Achats"
9 = "Produits"
10 = "Production"
11 = "Logistique"
12 = "Systèmes d’information"
13 = "Recherche, développement, innovation"
14 = "Ressources Humaines"
15 = "Gestion des Connaissances"
16 = "Formation"
17 = "Responsabilité sociale des entreprises"

["Linguistiques"]
1 = "Allemand"
2 = "Anglais"
3 = "Arabe"
4 = "Chinois"
5 = "Espagnol"
6 = "Français"
7 = "Italien"
8 = "Japonais"
9 = "Polonais"
10 = "Portugais"
11 = "Russe"
