[genre]
1 = "Cas d’école, cas d’application"
2 = "Chronique"
3 = "Critique"
4 = "Dossier"
5 = "Enquête"
6 = "Etude"
7 = "Exclusivité"
8 = "Fact checking"
9 = "Interview"
10 = "News"
11 = "Opinion"
12 = "Publi-rédactionnel"
13 = "Reportage"
14 = "Autre"

#1 = "Actualité"
#2 = "Almanac"
#3 = "Analyses"
#4 = "Appel à témoins"
#5 = "Archives"
#6 = "Avis de naissance"
#7 = "Avis"
#8 = "Background"
#9 = "Behind_the_Story"
#10 = "Biographie"
#11 = "Briefing"
#12 = "Chronique"
#13 = "Citation"
#14 = "Communiqué"
#15 = "Conseil"
#16 = "Contenu sponsorisé"
#17 = "Critique"
#18 = "Current"
#19 = "Daybook"
#20 = "Dossier"
#21 = "Exclusivité"
#22 = "Fact check"
#23 = "Feature"
#24 = "Histoire"
#25 = "Horoscope"
#26 = "Interview"
#27 = "Levé de rideau"
#28 = "Live"
#29 = "Musique"
#30 = "Nécrologie"
#31 = "Opinion"
#32 = "Preview"
#33 = "Profil"
#34 = "Prévision"
#35 = "Publi-rédactionnel"
#36 = "Questions / réponses"
#37 = "Son"
#38 = "Retrospective"
#39 = "Revue de presse"
#40 = "Réponse à une question"
#41 = "Satire"
#42 = "Sondage"
#43 = "Statistiques"
#44 = "Supported"
#45 = "Synthèse"
#46 = "Verbatim"
#47 = "Voix"
##1 = "From_the_Scene"
##1 = "ListingOfFacts"
##1 = "Side_bar_and_supporting_information"
