["Journalistes"]
1 = "Directeur de la rédaction"
2 = "Rédacteur en chef"
3 = "Rédacteur en chef Web"
4 = "Webmestre"
5 = "Chroniqueur"
6 = "Rédacteur Star"
7 = "Grand Reporter"
8 = "Correspondant de presse à l'étranger"
9 = "Correspondant de presse en région"
10 = "Chef de rubrique"
11 = "Chef d'enquête"
12 = "Rédacteur"
13 = "Journaliste-Reporter d'Images"
14 = "Photoreporter"
15 = "Data-Journaliste"
16 = "Rédacteur pigiste"
17 = "Illustrateur"
18 = "Cadreur"
19 = "Perchman"
20 = "Correcteur"
21 = "Réviseur"
22 = "Script"

["Communicants"]
1 = "Directeur de la communication"
2 = "Directeur des Relations de Presse"
3 = "Dirigeant d’un cabinet de Relations de Presse"
4 = "Consultant RP"
5 = "Attaché de presse indépendant"
6 = "Commissaire d’un Salon Professionnel"

["Décideurs"]
1 = "Actionnaire"
2 = "Cadre"
3 = "Conseiller municipal"
4 = "Conseiller technique"
5 = "Cofondateur"
6 = "Député"
7 = "DG"
8 = "Directeur"
9 = "Étudiant"
10 = "Investisseur"
11 = "Juge"
12 = "Maire"
13 = "Ministre"
14 = "Ouvrier"
15 = "PDG"
16 = "Président"
17 = "Responsable"
18 = "Sénateur"
19 = "Secrétaire"
20 = "Syndicaliste"
21 = "Vice-Président"

["Experts"]
1 = "Analyste"
2 = "Animateur"
3 = "Architecte"
4 = "Artisan"
5 = "Artiste"
6 = "Avocat"
7 = "Chercheur"
8 = "Coach"
9 = "Comptable"
10 = "Commercial"
11 = "Consultant"
12 = "Designer"
13 = "Docteur en médecine"
14 = "Écrivain"
15 = "Financier"
16 = "Ingénieur"
17 = "Juriste"
18 = "Logisticien"
19 = "Marketeur"
20 = "Producteur"
21 = "Personnel soignant"
22 = "Préventeur"
23 = "Professeur"
24 = "Publicitaire"
25 = "Technicien"
