[position]
1 = "Président"
2 = "Ministre"
3 = "Secrétaire d’Etat"
4 = "DG"
5 = "Directeur"
6 = "Conseiller"
7 = "Manager"
8 = "Collaborateur"
9 = "Actionnaire"
10 = "Membre du conseil d’administration"
11 = "Membre du conseil de surveillance"
12 = "Autre"
