["Arts, culture, People"]
1 = "Architecture"
2 = "Artisanat d’art"
3 = "Art vidéo"
4 = "Arts textiles, Haute-couture"
5 = "Arts de la scène"
6 = "Cinéma"
7 = "Dessin"
8 = "Musique"
9 = "Littérature & Philosophie"
10 = "People"
11 = "Peinture"
12 = "Presse, Médias, sites d’information"
13 = "Photographie"
14 = "Sculpture"
15 = "Autre"

#Was: ["Arts, Culture et Loisirs"]
#1 = "Architecture"
#2 = "Arts numériques"
#3 = "Arts plastiques"
#4 = "Arts de la scène"
#5 = "Arts visuels"
#6 = "BD"
#7 = "Cinéma"
#8 = "Décoration"
#9 = "Design"
#10 = "Gastronomie"
#11 = "Histoire"
#12 = "Jardinage"
#13 = "Jeux de société, jeux vidéos, Escape Game"
#14 = "Littérature"
#15 = "Mode"
#16 = "Musique"
#17 = "Parcs de loisirs"
#18 = "Tourisme"
#19 = "Voyage"

["Economie & industries"]
1 = "Agriculture, industries agroalimentaires"
2 = "Artisanat, TPE, PME, ETI, Grandes entreprises"
3 = "Associations, clubs, organisations syndicales"
4 = "Automobile, mobilités douces"
5 = "Aéronautique, spatial, défense"
6 = "Banque, assurance, bourse, finance"
7 = "Biotechnologies"
8 = "BTP, urbanisme"
9 = "Commerce, distribution"
10 = "Communication, publicité"
11 = "Energies, environnement"
12 = "Industrie"
13 = "Matériaux, mines"
14 = "Micro et nanoélectronique"
15 = "Mode, luxe"
16 = "Numérique"
17 = "Transports, logistique"
18 = "Services"
19 = "Sécurité, sûreté"
20 = "Tourisme, voyage, hôtellerie, restauration"
21 = "Autre"

# Was
#["Économie"]
#1 = "Assurance"
#2 = "Banque"
#3 = "Économie"
#4 = "Entreprises"
#5 = "Finances"
#6 = "Marchés"
#7 = "Monnaies, cryptomonnaies"
#8 = "Politiques économiques"
#9 = "Responsabilité sociétale des entreprises"
#10 = "Startups"
#
#["Industries"]
#1 = "Aéronautique"
#2 = "Agriculture, agriculture écologique, agriculture urbaine"
#3 = "Automobile"
#4 = "Biotechnologies"
#5 = "Bâtiment, travaux publics, urbanisme"
#6 = "Chimie, pétrochimie,"
#7 = "Commerce, e-commerce, distribution"
#8 = "Défense"
#9 = "Éducation, formation"
#10 = "Électronique"
#11 = "Énergies et environnement"
#12 = "Événementiel"
#13 = "Luxe"
#14 = "Industries agroalimentaires"
#15 = "Industries mécaniques"
#16 = "Industries du numérique, cloud, IoT, Wearables"
#17 = "Industrie pharmaceutique, cosmétique"
#18 = "Logiciels, Open Source"
#19 = "Logistique"
#20 = "Matériaux"
#21 = "Robotique"
#22 = "Santé, santé au travail"
#23 = "Sécurité-sûreté, cybersécurité"
#24 = "Services aux entreprises"
#25 = "Services à la personne"
#26 = "Services urbains"
#27 = "Spatial"
#28 = "Transports"

["Environnement"]
1 = "Agriculture durable"
2 = "Biodiversité"
3 = "Changement climatique, biodiversité, décroissance"
4 = "Energies renouvelables, économie d’énergie"
5 = "Environnement et santé"
6 = "Préservation des ressources naturelles"
7 = "Protection de l’environnement naturel"
8 = "Autre"

["Politique"]
1 = "Aménagement du territoire"
2 = "Budget, économie, finances"
3 = "Collectivités territoriales"
4 = "Défense"
5 = "Diplomatie, international"
6 = "Elections"
7 = "Enseignement, recherche"
8 = "Gouvernement, ministères"
9 = "Institutions politiques et consulaires"
10 = "Parlement"
11 = "Partis politiques"
12 = "Présidence de la République"
13 = "Police, Justice"
14 = "Santé publique"
15 = "Social"
16 = "Autre"

# Was:
#["Institutions politiques"]
#1 = "Villes"
#2 = "Métropoles"
#3 = "Intecommunalités"
#4 = "Départements"
#5 = "Régions"
#6 = "Assemblée nationale"
#7 = "Sénat"
#8 = "Exécutif"

["Santé & Médecine"]
1 = "Etablissements de soins"
2 = "Ethique médicale"
3 = "Industrie pharmaceutique"
4 = "Laboratoires d’analyse"
5 = "Médecine conventionnelle"
6 = "Médecine d’urgence"
7 = "Psychiatrie, psychanalyse, psychologie"
8 = "Recherche médicale"
9 = "Santé animale"
10 = "Santé publique"
11 = "Vieillissement de la population"
12 = "Thérapies alternatives, thérapies géniques"
13 = "Autre"

["Sciences"]
1 = "Sciences de l’information et de la communication"
2 = "Sciences de la vie et de la Terre"
3 = "Sciences humaines"
4 = "Science politique et économique"
5 = "Autres sciences"

# Was: ["Sciences, recherche et innovation"]
#1 = "Académies"
#2 = "Accélérateurs de startups"
#3 = "Centres de recherche"
#4 = "Centres techniques"
#5 = "Écoles de commerce"
#6 = "Écoles d’ingénieurs"
#7 = "Grandes écoles"
#8 = "Société de fiscalité de l’innovation"
#9 = "Sociétés scientifiques"
#10 = "Sociétés de transfert de technologie"
#11 = "Start-up Studios"
#12 = "Universités"

["Société"]
1 = "Démocratie, droits de l'homme, liberté d'expression, LGBTQ+"
2 = "Éducation"
3 = "Justice sociale, lanceurs d’alerte"
4 = "Mouvements sociaux"
5 = "Parité femmes-hommes"
6 = "Numérique et protection de la vie privée"
7 = "Religions, croyances"
8 = "Réseaux sociaux"
9 = "Scandale"
10 = "Autre"

# Was:
#1 = "Aides sociales"
#2 = "Animaux, bien-être animal"
#3 = "Consommation"
#4 = "Débats de société"
#5 = "Droits fondamentaux"
#6 = "Écologie"
#7 = "Élections"
#8 = "Emploi et travail"
#9 = "Éducation et formation"
#10 = "Famille"
#11 = "Genres"
#12 = "Justice"
#13 = "Police, gendarmerie"
#14 = "Religion"
#15 = "Retraites"
#16 = "Solidarités"


["Sports"]
1 = "Aviron, canoë-kayak, voile"
2 = "Arts martiaux, boxe, escrime"
3 = "Athlétisme, haltérophilie, triathlon, golf"
4 = "Basketball, Volley Ball, Handball, Football, Rugby, WaterPolo"
5 = "Cyclisme, VTT"
6 = "Echecs"
7 = "Gymnastique, gymnastique artistique, trampoline"
8 = "Jeux olympiques et paralympiques"
9 = "Natation, plongée, plongeon, water polo"
10 = "Patinage, patinage artistique"
11 = "Randonnée, marche nordique"
12 = "Ski, sports de glisse"
13 = "Sports équestres"
14 = "Sports mécaniques (auto, moto, bateaux, avions)"
15 = "Tennis, badminton, ping pong"
16 = "Tir à l’arc, au pistolet, à la carabine"
17 = "Autre sport"

# Was
#1 = "Équitation"
#2 = "Escrime"
#3 = "E-Sport"
#4 = "Footbal"
#5 = "Golf"
#6 = "Handball"
#7 = "Natation"
#8 = "Jeux Olympiques"
#9 = "Rugby"
#10 = "Sports individuels"
#11 = "Sports collectifs"
#12 = "Sports mécaniques"
#13 = "Sports nautiques"
#14 = "Sports de glisse"
#15 = "Tennis"
#16 = "Tennis de table"

["Technologies & Numérique"]
1 = "Apps, logiciels et équipements Grand public"
2 = "Apps, logiciels et équipements pro"
3 = "Blockchain, cryptomonnaies"
4 = "Cloud Computing, Data Centers, réseaux, 5G"
5 = "Cybersécurité, sécurité électronique"
6 = "Gestion et optimisation des ressources"
7 = "Intelligence Artificielle (IA), vision par ordinateur, traitement du langage naturel"
8 = "Internet des Objets (IoT, IIoT)"
9 = "Open Source"
10 = "Réalité virtuelle (RV), réalité augmentée (RA)"
11 = "Robotique"
12 = "Autre"

["Vie perso"]
1 = "Alimentation"
2 = "Loisirs, culture, sports, jeux vidéo"
3 = "Beauté, santé, sexualité"
4 = "Education, enseignement"
5 = "Famille, enfants, ados, seniors"
6 = "Développement personnel,"
7 = "Argent, finances, placements, retraite"
8 = "Maternité, handicap, dépendance, grand âge"
9 = "Logement, déco, bricolage, jardinage"
10 = "Mode, luxe, prêt-à-porter, bijoux"
11 = "Modes de vie, tendances, consommation"
12 = "Vie associative"
13 = "Voyages, déplacements"
14 = "Autre"

["Vie professionnelle"]
1 = "Salaire, avantages sociaux, avancement"
2 = "Emploi, formation"
3 = "Santé, sécurité et qualité de vie au travail, RSE, équilibre vie pro-vie perso"
4 = "Télétravail, Flex Office, Coworking"
5 = "Représentation syndicale, dialogue social"
6 = "Leadership, clés du management du XXIème siècle"
7 = "Bureautique, outils collaboratifs"
8 = "Autre"
