# "Rubriques" en français

[press]
1 = "A la Une"
2 = "Actualité"
3 = "Agenda"
4 = "Argent"
5 = "Arts"
6 = "Avis d’expert"
7 = "Cas d’application"
8 = "Culture"
9 = "Dernière heure"
10 = "Dossier"
11 = "Enquête"
12 = "Etude"
13 = "Fait Divers"
14 = "Guide d'achat"
15 = "Interview"
16 = "L'Évènement"
17 = "Marchés"
18 = "Nomination"
19 = "Nouveau Produit"
20 = "Perso"
21 = "Polémique"
22 = "Politique"
23 = "Portrait"
24 = "Reportage"
25 = "Résultats financier"
26 = "Résultat Scientifique"
27 = "Social"
28 = "Sports"
29 = "Tendances"
30 = "Vie des entreprises"
31 = "Vie pratique"

#Sujets, commandes et enquêtes
[cfc]
1 = "Appel à expert"
2 = "Appel à témoin"
3 = "Article à vendre"
4 = "Avis d’enquête"
5 = "Brief"
6 = "Commande d’un article"
7 = "Sujet à vendre"

#Communiqué de presse
[press-release]
1 = "Agenda"
2 = "Avis d’expert"
3 = "Cas d’application"
4 = "Création d’entreprise"
5 = "Événement"
6 = "Événement presse"
7 = "Étude"
8 = "Nomination"
9 = "Nouveau Produit"
10 = "Portrait"
11 = "Résultats financier"
12 = "Résultat Scientifique"
13 = "Social"
14 = "Vie des entreprises"
