["type-presse"]
1 = "Presse d’information générale / Information nationale & internationale"
2 = "Presse d’information générale / Information régionale et locale"
3 = "Presse d’information générale / Politique"
4 = "Presse d’information générale / Société & faits divers"
5 = "Presse d’information générale / Autre"
6 = "Presse économique et professionnelle / IAA, agriculture"
7 = "Presse économique et professionnelle / Auto, moto & mobilités"
8 = "Presse économique et professionnelle / Economie & Finances"
9 = "Presse économique et professionnelle / BTP"
10 = "Presse économique et professionnelle / Collectivités locales"
11 = "Presse économique et professionnelle / Distribution"
12 = "Presse économique et professionnelle / Entreprise & management"
13 = "Presse économique et professionnelle / Environnement"
14 = "Presse économique et professionnelle / Médical"
15 = "Presse économique et professionnelle / Numérique Pro & technologies"
16 = "Presse économique et professionnelle / Transport & Logistique"
17 = "Presse économique et professionnelle / Juridique"
18 = "Presse économique et professionnelle / Industrie"
19 = "Presse économique et professionnelle / Santé au travail"
20 = "Presse économique et professionnelle / Autre"
21 = "Presse spécialisée grand public / Animaux"
22 = "Presse spécialisée grand public / Argent, placements, patrimoine"
23 = "Presse spécialisée grand public / Arts & culture"
24 = "Presse spécialisée grand public / Automobile & mobilités"
25 = "Presse spécialisée grand public / Déco, brico, jardinage"
26 = "Presse spécialisée grand public / Education"
27 = "Presse spécialisée grand public / Femme (mode, beauté, santé)"
28 = "Presse spécialisée grand public / Homme (mode, beauté, santé)"
29 = "Presse spécialisée grand public / Loisirs, cuisine, gastronomie"
30 = "Presse spécialisée grand public / Numérique & jeux vidéo"
31 = "Presse spécialisée grand public / People"
32 = "Presse spécialisée grand public / Sciences & Environnement"
33 = "Presse spécialisée grand public / Sports"
34 = "Presse spécialisée grand public / Tourisme, voyage"
35 = "Presse spécialisée grand public / Autre"
36 = "Autre type de presse"
