"""remove organisation fields

Revision ID: 01dd37023542
Revises: 04263f834f85
Create Date: 2026-03-18 14:52:15.716545

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01dd37023542'
down_revision = '04263f834f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crp_organisation_type'))
        batch_op.drop_column('main_prizes')
        batch_op.drop_column('logo_image')
        batch_op.drop_column('stripe_subscription_status')
        batch_op.drop_column('stripe_latest_invoice_url')
        batch_op.drop_column('number_customers')
        batch_op.drop_column('agree_arcom')
        batch_op.drop_column('type_organisation_detail')
        batch_op.drop_column('tva')
        batch_op.drop_column('pays_zip_ville')
        batch_op.drop_column('membre_sapi')
        batch_op.drop_column('creator_profile_code')
        batch_op.drop_column('membre_satev')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('audience_cible')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('payer_coords')
        batch_op.drop_column('type_organisation')
        batch_op.drop_column('payer_name')
        batch_op.drop_column('type_entreprise_media')
        batch_op.drop_column('type')
        batch_op.drop_column('nom_groupe')
        batch_op.drop_column('metiers')
        batch_op.drop_column('agree_cppap')
        batch_op.drop_column('main_events')
        batch_op.drop_column('frequence_publication')
        batch_op.drop_column('tel_standard')
        batch_op.drop_column('stripe_subs_creation_date')
        batch_op.drop_column('screenshot_id')
        batch_op.drop_column('pays_zip_ville_detail')
        batch_op.drop_column('secteurs_activite_medias')
        batch_op.drop_column('tirage')
        batch_op.drop_column('leader_name')
        batch_op.drop_column('number_cppap')
        batch_op.drop_column('site_url')
        batch_op.drop_column('secteurs_activite_medias_detail')
        batch_op.drop_column('transformation_majeure')
        batch_op.drop_column('metiers_presse')
        batch_op.drop_column('secteurs_activite_rp_detail')
        batch_op.drop_column('type_presse_et_media')
        batch_op.drop_column('secteurs_activite_detail')
        batch_op.drop_column('type_agence_rp')
        batch_op.drop_column('siren')
        batch_op.drop_column('metiers_detail')
        batch_op.drop_column('taille_orga')
        batch_op.drop_column('positionnement_editorial')
        batch_op.drop_column('secteurs_activite')
        batch_op.drop_column('stripe_product_quantity')
        batch_op.drop_column('leader_coords')
        batch_op.drop_column('main_customers')
        batch_op.drop_column('secteurs_activite_rp')
        batch_op.drop_column('validity_date')
        batch_op.drop_column('transformation_majeure_detail')
        batch_op.drop_column('description')
        batch_op.drop_column('stripe_subs_current_period_start')
        batch_op.drop_column('membre_saphir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membre_saphir', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_subs_current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transformation_majeure_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('validity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite_rp', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('main_customers', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('leader_coords', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_product_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('positionnement_editorial', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('taille_orga', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metiers_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('siren', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_agence_rp', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_presse_et_media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite_rp_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metiers_presse', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transformation_majeure', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite_medias_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('site_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('number_cppap', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('leader_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tirage', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secteurs_activite_medias', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pays_zip_ville_detail', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('screenshot_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_subs_creation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tel_standard', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('frequence_publication', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('main_events', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('agree_cppap', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metiers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nom_groupe', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('AUTO', 'MEDIA', 'AGENCY', 'COM', 'OTHER', name='organisationtypeenum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_entreprise_media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_organisation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payer_coords', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cover_image', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('audience_cible', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('membre_satev', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('creator_profile_code', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('membre_sapi', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pays_zip_ville', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tva', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_organisation_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('agree_arcom', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('number_customers', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_latest_invoice_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_subscription_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_image', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('main_prizes', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_crp_organisation_type'), ['type'], unique=False)

    # ### end Alembic commands ###
