"""businesswall attributes

Revision ID: 04263f834f85
Revises: 2ea5c4d30cb0
Create Date: 2026-03-16 16:21:31.356207

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.orm import Session
from sqlalchemy import select
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04263f834f85"
down_revision = "2ea5c4d30cb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code_postal", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("departement", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("ville", sa.String(), nullable=True))

    # ### end Alembic commands ###

    _populate_location_fields()


def _populate_location_fields():
    bind = op.get_bind()
    session = Session(bind=bind)
    from app.modules.bw.bw_activation.models.business_wall import BusinessWall

    stmt = select(BusinessWall)
    business_walls = session.scalars(stmt).all()

    for bw in business_walls:
        bw.update_location_fields()

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("ville")
        batch_op.drop_column("departement")
        batch_op.drop_column("code_postal")

    # ### end Alembic commands ###
