"""add remove organisation.bw_type

Revision ID: 0ce352f51d81
Revises: 3fe3b3403603
Create Date: 2026-04-01 11:17:49.291072

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ce352f51d81"
down_revision = "3fe3b3403603"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.drop_column("bw_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "bw_type",
                postgresql.ENUM(
                    "AGENCY",
                    "MEDIA",
                    "CORPORATE",
                    "PRESSUNION",
                    "COM",
                    "ORGANISATION",
                    "TRANSFORMER",
                    "ACADEMICS",
                    name="bwtypeenum",
                ),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
