"""add eventroom_id field to EventPost

Revision ID: 0fb901d6eef6
Revises: b199c5c867bf
Create Date: 2025-10-14 16:32:55.262012

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0fb901d6eef6"
down_revision = "b199c5c867bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eventroom_id", sa.BigInteger(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cnt_base_eventroom_id"), ["eventroom_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cnt_base_eventroom_id"))
        batch_op.drop_column("eventroom_id")

    # ### end Alembic commands ###
