"""add_column_photo_carte_presse_image

Revision ID: 10aea8b9a3b4
Revises: 8b0da77a7479
Create Date: 2025-11-27 09:59:19.282967

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10aea8b9a3b4"
down_revision = "8b0da77a7479"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "photo_carte_presse_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.drop_column("profile_image_url")
        batch_op.drop_column("photo_carte_presse_filename")
        batch_op.drop_column("photo_carte_presse")
        batch_op.drop_column("photo_filename")
        batch_op.drop_column("photo")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("photo", postgresql.BYTEA(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "photo_filename", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "photo_carte_presse",
                postgresql.BYTEA(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "photo_carte_presse_filename",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "profile_image_url", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("photo_carte_presse_image")
    # ### end Alembic commands ###
