"""refactor EventPost

Revision ID: 1616d72057d1
Revises: 0fb901d6eef6
Create Date: 2025-10-14 17:30:46.046962

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1616d72057d1"
down_revision = "0fb901d6eef6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evt_event_post",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("eventroom_id", sa.BigInteger(), nullable=True),
        sa.Column("pays_zip_ville", sa.String(), nullable=False),
        sa.Column("pays_zip_ville_detail", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["cnt_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evt_event_post_eventroom_id"), ["eventroom_id"], unique=False
        )

    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cnt_base_eventroom_id"))
        batch_op.drop_column("eventroom_id")

    with op.batch_alter_table("evt_participation", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("evt_participation_event_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,
            "evt_event_post",
            ["event_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("evt_participation", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("evt_participation_event_id_fkey"),
            "cnt_base",
            ["event_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.alter_column(
            "pays_zip_ville_detail",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "pays_zip_ville",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )

    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("eventroom_id", sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_cnt_base_eventroom_id"), ["eventroom_id"], unique=False
        )

    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evt_event_post_eventroom_id"))

    op.drop_table("evt_event_post")
    # ### end Alembic commands ###
