"""add User.photo_image_copyright

Revision ID: 17850c9cf4a6
Revises: 1b4d3cb0fe33
Create Date: 2026-03-23 10:37:05.724782

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '17850c9cf4a6'
down_revision = '1b4d3cb0fe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('aut_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_image_copyright', sa.String(), nullable=True))

    op.execute("UPDATE aut_user SET photo_image_copyright = ''")
    with op.batch_alter_table('aut_user', schema=None) as batch_op:
        batch_op.alter_column('photo_image_copyright', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('aut_user', schema=None) as batch_op:
        batch_op.drop_column('photo_image_copyright')


    # ### end Alembic commands ###
