"""empty message

Revision ID: 18fc5059a3ae
Revises: 14651fab9748
Create Date: 2026-02-15 09:53:01.754955

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18fc5059a3ae'
down_revision = '14651fab9748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blb_blob')
    # Skipped: adm_promotion profile enum rename (not necessary, causes issues)

    with op.batch_alter_table('evt_event_post', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('nrm_avis_enquete', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_commande', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_contact_avis_enquete', schema=None) as batch_op:
        batch_op.alter_column('email_relation_presse',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_notification_publication', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('nrm_sujet', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nrm_sujet', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_notification_publication', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('nrm_contact_avis_enquete', schema=None) as batch_op:
        batch_op.alter_column('email_relation_presse',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_commande', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('nrm_avis_enquete', schema=None) as batch_op:
        batch_op.alter_column('pays_zip_ville_detail',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('pays_zip_ville',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('evt_event_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))

    # Skipped: adm_promotion profile enum rename (not necessary)

    op.create_table('blb_blob',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('s3_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sha256', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('blb_blob_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('blb_blob_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
