"""add field cover_image_copyright

Revision ID: 1b4d3cb0fe33
Revises: beb6712180e4
Create Date: 2026-03-20 15:52:18.449018

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1b4d3cb0fe33"
down_revision = "beb6712180e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cover_image_copyright", sa.String(), nullable=True)
        )

    op.execute("UPDATE aut_user SET cover_image_copyright = ''")
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.alter_column("cover_image_copyright", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.drop_column("cover_image_copyright")

    # ### end Alembic commands ###
