"""move PostStatus->PublicationStatus

Revision ID: 1f7aff5a224c
Revises: b199c5c867bf
Create Date: 2025-10-14 11:11:45.238207

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1f7aff5a224c"
down_revision = "b199c5c867bf"
branch_labels = None
depends_on = None

NEW_PUBLICATION_STATUS_VALUES = (
    "DRAFT",
    "PRIVATE",
    "PENDING",
    "PUBLIC",
    "REJECTED",
    "EXPIRED",
    "ARCHIVED",
    "DELETED",
)
NEW_PUBLICATION_STATUS_COMMA_STRING = ", ".join(
    f"'{v}'" for v in NEW_PUBLICATION_STATUS_VALUES
)


def _drop_type_if_exists(enum_name: str) -> None:
    """Safely drop custom PostgreSQL ENUM type."""
    op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE;")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    _drop_type_if_exists("publicationstatus")
    op.execute(
        f"CREATE TYPE publicationstatus AS ENUM ({NEW_PUBLICATION_STATUS_COMMA_STRING})"
    )

    _drop_type_if_exists("publishertype")
    op.execute(f"CREATE TYPE publishertype AS ENUM ('AGENCY', 'MEDIA', 'COM', 'OTHER')")

    op.execute(
        "ALTER TABLE crm_communique ALTER COLUMN status TYPE publicationstatus USING status::text::publicationstatus, ALTER COLUMN status SET NOT NULL"
    )

    op.execute(
        "ALTER TABLE evr_event ALTER COLUMN status TYPE publicationstatus USING status::text::publicationstatus, ALTER COLUMN status SET NOT NULL"
    )

    op.execute(
        "ALTER TABLE frt_content ALTER COLUMN status TYPE publicationstatus USING status::text::publicationstatus, ALTER COLUMN status SET NOT NULL"
    )

    op.execute(
        "ALTER TABLE frt_content ALTER COLUMN publisher_type TYPE publishertype USING publisher_type::text::publishertype, ALTER COLUMN status SET NOT NULL"
    )

    _drop_type_if_exists("com_publicationstatus")
    _drop_type_if_exists("evr_publicationstatus")
    _drop_type_if_exists("poststatus3")
    _drop_type_if_exists("publishertype2")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    _drop_type_if_exists("com_publicationstatus")
    op.execute(
        f"CREATE TYPE com_publicationstatus AS ENUM ({NEW_PUBLICATION_STATUS_COMMA_STRING})"
    )

    _drop_type_if_exists("evr_publicationstatus")
    op.execute(
        f"CREATE TYPE evr_publicationstatus AS ENUM ({NEW_PUBLICATION_STATUS_COMMA_STRING})"
    )

    _drop_type_if_exists("poststatus3")
    op.execute("CREATE TYPE poststatus3 AS ENUM ('DRAFT', 'PUBLIC', 'ARCHIVED')")

    _drop_type_if_exists("publishertype2")
    op.execute("CREATE TYPE publishertype2 AS ENUM ('AGENCY', 'MEDIA')")

    op.execute(
        "ALTER TABLE frt_content ALTER COLUMN publisher_type TYPE publishertype2 USING publisher_type::text::publishertype2, ALTER COLUMN status SET NOT NULL"
    )
    op.execute(
        "ALTER TABLE frt_content ALTER COLUMN status TYPE poststatus3 USING status::text::poststatus3, ALTER COLUMN status SET NOT NULL"
    )

    op.execute(
        "ALTER TABLE evr_event ALTER COLUMN status TYPE evr_publicationstatus USING status::text::evr_publicationstatus, ALTER COLUMN status SET NOT NULL"
    )

    op.execute(
        "ALTER TABLE crm_communique ALTER COLUMN status TYPE com_publicationstatus USING status::text::com_publicationstatus, ALTER COLUMN status SET NOT NULL"
    )

    _drop_type_if_exists("publicationstatus")
    _drop_type_if_exists("publishertype")

    # ### end Alembic commands ###
