"""Add cover_image and logo_image to Organisation

Revision ID: 1ff7ca88f806
Revises: ad80dabfbc9a
Create Date: 2025-12-08 16:35:50.531526

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import advanced_alchemy

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ff7ca88f806'
down_revision = 'ad80dabfbc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_tmp_blob')
    # with op.batch_alter_table('adm_promotion', schema=None) as batch_op:
    #     batch_op.alter_column('profile',
    #            existing_type=postgresql.ENUM('PM_DIR', 'PM_JR_CP_SAL', 'PM_JR_PIG', 'PM_JR_CP_ME', 'PM_JR_ME', 'PM_DIR_INST', 'PM_JR_INST', 'PM_DIR_SYND', 'PR_DIR', 'PR_CS', 'PR_CS_IND', 'PR_DIR_COM', 'PR_CS_COM', 'XP_DIR_ANY', 'XP_ANY', 'XP_PR', 'XP_IND', 'XP_DIR_SU', 'XP_INV_PUB', 'XP_DIR_EVT', 'TP_DIR_ORG', 'TR_CS_ORG', 'TR_CS_ORG_PR', 'TR_CS_ORG_IND', 'TR_DIR_SU_ORG', 'TR_INV_ORG', 'TR_DIR_POLE', 'AC_DIR', 'AC_DIR_JR', 'AC_ENS', 'AC_DOC', 'AC_ST', 'AC_ST_ENT', name='adm_profileenum'),
    #            type_=sa.Enum('PM_DIR', 'PM_JR_CP_SAL', 'PM_JR_PIG', 'PM_JR_CP_ME', 'PM_JR_ME', 'PM_DIR_INST', 'PM_JR_INST', 'PM_DIR_SYND', 'PR_DIR', 'PR_CS', 'PR_CS_IND', 'PR_DIR_COM', 'PR_CS_COM', 'XP_DIR_ANY', 'XP_ANY', 'XP_PR', 'XP_IND', 'XP_DIR_SU', 'XP_INV_PUB', 'XP_DIR_EVT', 'TP_DIR_ORG', 'TR_CS_ORG', 'TR_CS_ORG_PR', 'TR_CS_ORG_IND', 'TR_DIR_SU_ORG', 'TR_INV_ORG', 'TR_DIR_POLE', 'AC_DIR', 'AC_DIR_JR', 'AC_ENS', 'AC_DOC', 'AC_ST', 'AC_ST_ENT', name='profileenum'),
    #            existing_nullable=True)

    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_image', advanced_alchemy.types.file_object.data_type.StoredObject(backend='s3'), nullable=True))
        batch_op.add_column(sa.Column('cover_image', advanced_alchemy.types.file_object.data_type.StoredObject(backend='s3'), nullable=True))
        batch_op.drop_column('logo_id')
        batch_op.drop_column('cover_image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('logo_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('cover_image')
        batch_op.drop_column('logo_image')

    # with op.batch_alter_table('adm_promotion', schema=None) as batch_op:
    #     batch_op.alter_column('profile',
    #            existing_type=sa.Enum('PM_DIR', 'PM_JR_CP_SAL', 'PM_JR_PIG', 'PM_JR_CP_ME', 'PM_JR_ME', 'PM_DIR_INST', 'PM_JR_INST', 'PM_DIR_SYND', 'PR_DIR', 'PR_CS', 'PR_CS_IND', 'PR_DIR_COM', 'PR_CS_COM', 'XP_DIR_ANY', 'XP_ANY', 'XP_PR', 'XP_IND', 'XP_DIR_SU', 'XP_INV_PUB', 'XP_DIR_EVT', 'TP_DIR_ORG', 'TR_CS_ORG', 'TR_CS_ORG_PR', 'TR_CS_ORG_IND', 'TR_DIR_SU_ORG', 'TR_INV_ORG', 'TR_DIR_POLE', 'AC_DIR', 'AC_DIR_JR', 'AC_ENS', 'AC_DOC', 'AC_ST', 'AC_ST_ENT', name='profileenum'),
    #            type_=postgresql.ENUM('PM_DIR', 'PM_JR_CP_SAL', 'PM_JR_PIG', 'PM_JR_CP_ME', 'PM_JR_ME', 'PM_DIR_INST', 'PM_JR_INST', 'PM_DIR_SYND', 'PR_DIR', 'PR_CS', 'PR_CS_IND', 'PR_DIR_COM', 'PR_CS_COM', 'XP_DIR_ANY', 'XP_ANY', 'XP_PR', 'XP_IND', 'XP_DIR_SU', 'XP_INV_PUB', 'XP_DIR_EVT', 'TP_DIR_ORG', 'TR_CS_ORG', 'TR_CS_ORG_PR', 'TR_CS_ORG_IND', 'TR_DIR_SU_ORG', 'TR_INV_ORG', 'TR_DIR_POLE', 'AC_DIR', 'AC_DIR_JR', 'AC_ENS', 'AC_DOC', 'AC_ST', 'AC_ST_ENT', name='adm_profileenum'),
    #            existing_nullable=True)

    op.create_table('kyc_tmp_blob',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_tmp_blob_pkey')),
    sa.UniqueConstraint('id', name=op.f('kyc_tmp_blob_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
