"""add type_organisation to bw_business_wall

Revision ID: 1299393538bd
Revises: 54637ddf161a
Create Date: 2026-03-02 17:11:25.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import advanced_alchemy

# revision identifiers, used by Alembic.
revision = "1299393538bd"
down_revision = "54637ddf161a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_organisation",
                sa.JSON()
                .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_organisation_detail",
                sa.JSON()
                .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
                server_default="[]",
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("type_organisation_detail")
        batch_op.drop_column("type_organisation")
    # ### end Alembic commands ###
