"""add gallery_images to bw_business_wall

Revision ID: 54637ddf161a
Revises: f7ad3e8a0230
Create Date: 2026-03-02 15:35:50.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54637ddf161a"
down_revision = "643c84a670aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "gallery_images",
                sa.JSON()
                .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
                server_default="[]",
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("gallery_images")
    # ### end Alembic commands ###
