"""add interest detail fields to bw_business_wall

Revision ID: 20260302_175500
Revises: 1299393538bd
Create Date: 2026-03-02 17:55:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260302_175500"
down_revision = "1299393538bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "interest_political_detail",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_economics_detail",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_association_detail",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
                server_default="[]",
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("interest_association_detail")
        batch_op.drop_column("interest_economics_detail")
        batch_op.drop_column("interest_political_detail")
    # ### end Alembic commands ###
