"""empty message

Revision ID: 217dc369b44c
Revises: d23d2c0aa4b0
Create Date: 2025-11-14 16:22:43.942453

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "217dc369b44c"
down_revision = "d23d2c0aa4b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("adm_promotion", schema=None) as batch_op:
    #     batch_op.alter_column(
    #         "profile",
    #         existing_type=postgresql.ENUM(
    #             "PM_DIR",
    #             "PM_JR_CP_SAL",
    #             "PM_JR_PIG",
    #             "PM_JR_CP_ME",
    #             "PM_JR_ME",
    #             "PM_DIR_INST",
    #             "PM_JR_INST",
    #             "PM_DIR_SYND",
    #             "PR_DIR",
    #             "PR_CS",
    #             "PR_CS_IND",
    #             "PR_DIR_COM",
    #             "PR_CS_COM",
    #             "XP_DIR_ANY",
    #             "XP_ANY",
    #             "XP_PR",
    #             "XP_IND",
    #             "XP_DIR_SU",
    #             "XP_INV_PUB",
    #             "XP_DIR_EVT",
    #             "TP_DIR_ORG",
    #             "TR_CS_ORG",
    #             "TR_CS_ORG_PR",
    #             "TR_CS_ORG_IND",
    #             "TR_DIR_SU_ORG",
    #             "TR_INV_ORG",
    #             "TR_DIR_POLE",
    #             "AC_DIR",
    #             "AC_DIR_JR",
    #             "AC_ENS",
    #             "AC_DOC",
    #             "AC_ST",
    #             "AC_ST_ENT",
    #             name="adm_profileenum",
    #         ),
    #         type_=sa.Enum(
    #             "PM_DIR",
    #             "PM_JR_CP_SAL",
    #             "PM_JR_PIG",
    #             "PM_JR_CP_ME",
    #             "PM_JR_ME",
    #             "PM_DIR_INST",
    #             "PM_JR_INST",
    #             "PM_DIR_SYND",
    #             "PR_DIR",
    #             "PR_CS",
    #             "PR_CS_IND",
    #             "PR_DIR_COM",
    #             "PR_CS_COM",
    #             "XP_DIR_ANY",
    #             "XP_ANY",
    #             "XP_PR",
    #             "XP_IND",
    #             "XP_DIR_SU",
    #             "XP_INV_PUB",
    #             "XP_DIR_EVT",
    #             "TP_DIR_ORG",
    #             "TR_CS_ORG",
    #             "TR_CS_ORG_PR",
    #             "TR_CS_ORG_IND",
    #             "TR_DIR_SU_ORG",
    #             "TR_INV_ORG",
    #             "TR_DIR_POLE",
    #             "AC_DIR",
    #             "AC_DIR_JR",
    #             "AC_ENS",
    #             "AC_DOC",
    #             "AC_ST",
    #             "AC_ST_ENT",
    #             name="profileenum",
    #         ),
    #         existing_nullable=True,
    #     )

    # Convert crm_communique.status from old enum to new enum
    # Step 1: Convert to VARCHAR
    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="com_publicationstatus",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="status::text",
        )

    # Step 2: Convert VARCHAR to new enum
    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            existing_nullable=False,
            postgresql_using="status::publicationstatus",
        )

    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "published_at",
                sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "expired_at",
                sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "pays_zip_ville",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "pays_zip_ville_detail",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )

    # Convert evr_event.status from old enum to new enum
    # Step 1: Convert to VARCHAR
    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="evr_publicationstatus",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="status::text",
        )

    # Step 2: Convert VARCHAR to new enum
    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            existing_nullable=False,
            postgresql_using="status::publicationstatus",
        )

    # Convert frt_content.publisher_type from old enum to new enum
    # Step 1: Convert to VARCHAR
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "publisher_type",
            existing_type=postgresql.ENUM("AGENCY", "MEDIA", name="publishertype2"),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="publisher_type::text",
        )

    # Step 2: Convert VARCHAR to new enum
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "publisher_type",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum("AGENCY", "MEDIA", "COM", "OTHER", name="publishertype"),
            existing_nullable=False,
            postgresql_using="publisher_type::publishertype",
        )

    # Convert frt_content.status from old enum to new enum
    # Step 1: Convert to VARCHAR
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "DRAFT", "PUBLIC", "ARCHIVED", name="poststatus3"
            ),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="status::text",
        )

    # Step 2: Convert VARCHAR to new enum
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            existing_nullable=False,
            postgresql_using="status::publicationstatus",
        )

    with op.batch_alter_table("nrm_article", schema=None) as batch_op:
        batch_op.alter_column(
            "pays_zip_ville",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "pays_zip_ville_detail",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nrm_article", schema=None) as batch_op:
        batch_op.alter_column(
            "pays_zip_ville_detail",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "pays_zip_ville",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )

    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "publisher_type",
            existing_type=sa.Enum(
                "AGENCY", "MEDIA", "COM", "OTHER", name="publishertype"
            ),
            type_=postgresql.ENUM("AGENCY", "MEDIA", name="publishertype2"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            type_=postgresql.ENUM("DRAFT", "PUBLIC", "ARCHIVED", name="poststatus3"),
            existing_nullable=False,
        )

    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.alter_column(
            "pays_zip_ville_detail",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "pays_zip_ville",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            type_=postgresql.ENUM(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="evr_publicationstatus",
            ),
            existing_nullable=False,
        )
        batch_op.drop_column("expired_at")
        batch_op.drop_column("published_at")

    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="publicationstatus",
            ),
            type_=postgresql.ENUM(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="com_publicationstatus",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("adm_promotion", schema=None) as batch_op:
        batch_op.alter_column(
            "profile",
            existing_type=sa.Enum(
                "PM_DIR",
                "PM_JR_CP_SAL",
                "PM_JR_PIG",
                "PM_JR_CP_ME",
                "PM_JR_ME",
                "PM_DIR_INST",
                "PM_JR_INST",
                "PM_DIR_SYND",
                "PR_DIR",
                "PR_CS",
                "PR_CS_IND",
                "PR_DIR_COM",
                "PR_CS_COM",
                "XP_DIR_ANY",
                "XP_ANY",
                "XP_PR",
                "XP_IND",
                "XP_DIR_SU",
                "XP_INV_PUB",
                "XP_DIR_EVT",
                "TP_DIR_ORG",
                "TR_CS_ORG",
                "TR_CS_ORG_PR",
                "TR_CS_ORG_IND",
                "TR_DIR_SU_ORG",
                "TR_INV_ORG",
                "TR_DIR_POLE",
                "AC_DIR",
                "AC_DIR_JR",
                "AC_ENS",
                "AC_DOC",
                "AC_ST",
                "AC_ST_ENT",
                name="profileenum",
            ),
            type_=postgresql.ENUM(
                "PM_DIR",
                "PM_JR_CP_SAL",
                "PM_JR_PIG",
                "PM_JR_CP_ME",
                "PM_JR_ME",
                "PM_DIR_INST",
                "PM_JR_INST",
                "PM_DIR_SYND",
                "PR_DIR",
                "PR_CS",
                "PR_CS_IND",
                "PR_DIR_COM",
                "PR_CS_COM",
                "XP_DIR_ANY",
                "XP_ANY",
                "XP_PR",
                "XP_IND",
                "XP_DIR_SU",
                "XP_INV_PUB",
                "XP_DIR_EVT",
                "TP_DIR_ORG",
                "TR_CS_ORG",
                "TR_CS_ORG_PR",
                "TR_CS_ORG_IND",
                "TR_DIR_SU_ORG",
                "TR_INV_ORG",
                "TR_DIR_POLE",
                "AC_DIR",
                "AC_DIR_JR",
                "AC_ENS",
                "AC_DOC",
                "AC_ST",
                "AC_ST_ENT",
                name="adm_profileenum",
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
