"""rename deprecated Addressable departement

Revision ID: 219fd4f5f8ae
Revises: 038a4b19c59e
Create Date: 2026-02-05 15:04:12.503707

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "219fd4f5f8ae"
down_revision = "038a4b19c59e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.alter_column("departement", new_column_name="departement_deprecated")

    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.alter_column("departement", new_column_name="departement_deprecated")

    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.alter_column("departement", new_column_name="departement_deprecated")

    with op.batch_alter_table("soc_group", schema=None) as batch_op:
        batch_op.alter_column("departement", new_column_name="departement_deprecated")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("soc_group", schema=None) as batch_op:
        batch_op.alter_column("departement_deprecated", new_column_name="departement")

    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.alter_column("departement_deprecated", new_column_name="departement")

    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.alter_column("departement_deprecated", new_column_name="departement")

    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.alter_column("departement_deprecated", new_column_name="departement")

    # ### end Alembic commands ###
