"""empty message

Revision ID: 239dbcc5baef
Revises: 4440982fded4
Create Date: 2025-04-18 11:03:00.816900

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '239dbcc5baef'
down_revision = '4440982fded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapo', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contenu', sa.String(), nullable=False))

    with op.batch_alter_table('kyc_profile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('kyc_tmp_blob', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_tmp_blob', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('kyc_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.drop_column('contenu')
        batch_op.drop_column('chapo')

    # ### end Alembic commands ###
