"""add media_id column to Post

Revision ID: 249c5b1dbf2b
Revises: 26a562e28bfa
Create Date: 2025-10-29 15:28:08.493974

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "249c5b1dbf2b"
down_revision = "26a562e28bfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["media_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("media_id")
    # ### end Alembic commands ###
