"""rename cover_image_url -> cover_image_id

Revision ID: 26a562e28bfa
Revises: d5e8e4552f1e
Create Date: 2025-10-27 16:43:17.831091

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "26a562e28bfa"
down_revision = "d5e8e4552f1e"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_image_id", sa.String(), nullable=True))
    op.execute("UPDATE aut_user SET cover_image_id = '' WHERE cover_image_id IS NULL")
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.alter_column(
            "cover_image_id", existing_type=sa.String(), nullable=False
        )
        batch_op.drop_column("cover_image_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_image_url", sa.String(), nullable=True))
    op.execute("UPDATE aut_user SET cover_image_url = '' WHERE cover_image_id IS NULL")
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.alter_column(
            "cover_image_url", existing_type=sa.String(), nullable=False
        )
        batch_op.drop_column("cover_image_id")
    # ### end Alembic commands ###
