"""add business_wall_id to org_invitations

Revision ID: 28743aebde64
Revises: a5bd49ba521e
Create Date: 2026-07-28 09:31:43.471995

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28743aebde64"
down_revision = "a5bd49ba521e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("org_invitations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "business_wall_id",
                advanced_alchemy.types.guid.GUID(length=16),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "fk_org_invitations_bw_id",
            "bw_business_wall",
            ["business_wall_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("org_invitations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_org_invitations_bw_id", type_="foreignkey")
        batch_op.drop_column("business_wall_id")

    # ### end Alembic commands ###
