"""add column User.cover_image

Revision ID: 2d226d278d3b
Revises: f41e8fa6e55b
Create Date: 2025-11-26 15:53:22.435529

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d226d278d3b"
down_revision = "f41e8fa6e55b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cover_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.drop_column("cover_image_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cover_image_id", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("cover_image")
    # ### end Alembic commands ###
