"""add missions field to BusinessWall

Revision ID: 2ea5c4d30cb0
Revises: 20260302_175500
Create Date: 2026-03-05 16:46:28.000000

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ea5c4d30cb0"
down_revision = "20260302_175500"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("missions", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("missions")
    # ### end Alembic commands ###
