"""use FileObject for organisation logo

Revision ID: 32f45ec9a86a
Revises: ad80dabfbc9a
Create Date: 2025-12-08 19:49:55.637083

"""

import advanced_alchemy
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "32f45ec9a86a"
down_revision = "ad80dabfbc9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "logo_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "cover_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.drop_column("cover_image_id")
        batch_op.drop_column("logo_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("logo_id", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "cover_image_id", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("cover_image")
        batch_op.drop_column("logo_image")

    # ### end Alembic commands ###
