"""empty message

Revision ID: 3fe3b3403603
Revises: 7cbe10b7736c
Create Date: 2026-03-31 17:22:48.330970

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fe3b3403603'
down_revision = '7cbe10b7736c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: removed spurious adm_promotion.profile enum rename
    # (adm_profileenum -> profileenum) - same values, Alembic false positive.

    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.alter_column('gallery_images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('type_organisation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('type_organisation_detail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('interest_political_detail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('interest_economics_detail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('interest_association_detail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_index(batch_op.f('ix_bw_business_wall_type'))
        batch_op.drop_column('type')

    with op.batch_alter_table('soc_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('soc_likes_content_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soc_likes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('soc_likes_content_id_fkey'), 'frt_content', ['content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('AUTO', 'MEDIA', 'AGENCY', 'COM', 'OTHER', name='organisationtypeenum'), server_default=sa.text("'AUTO'::organisationtypeenum"), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_bw_business_wall_type'), ['type'], unique=False)
        batch_op.alter_column('interest_association_detail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('interest_economics_detail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('interest_political_detail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('type_organisation_detail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('type_organisation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('gallery_images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    # ### end Alembic commands ###
