"""remove deprecated name_press

Revision ID: 41844c38f6a0
Revises: 888ac4f01dcb
Create Date: 2026-08-05 11:12:45.531476

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "41844c38f6a0"
down_revision = "888ac4f01dcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("name_press")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name_press",
                sa.VARCHAR(),
                server_default=sa.text("''::character varying"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
