"""add new BW tables

Revision ID: 47bc345da251
Revises: d7ff7af33908
Create Date: 2026-02-11 10:13:30.883129

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "47bc345da251"
down_revision = "d7ff7af33908"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bw_business_wall",
        sa.Column("bw_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("payer_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column(
            "activated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_business_wall")),
    )
    op.create_table(
        "bw_bw_content",
        sa.Column(
            "business_wall_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("official_name", sa.String(), nullable=False),
        sa.Column("organization_type", sa.String(length=100), nullable=False),
        sa.Column(
            "logo",
            advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
            nullable=True,
        ),
        sa.Column(
            "banner",
            advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
            nullable=True,
        ),
        sa.Column(
            "gallery",
            advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("baseline", sa.String(), nullable=False),
        sa.Column("siren", sa.String(), nullable=False),
        sa.Column("tva_number", sa.String(), nullable=False),
        sa.Column("cppap", sa.String(), nullable=False),
        sa.Column("website", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("twitter_url", sa.String(), nullable=False),
        sa.Column("linkedin_url", sa.String(), nullable=False),
        sa.Column("facebook_url", sa.String(), nullable=False),
        sa.Column(
            "topics",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "geographic_zones",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "sectors",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "member_ids",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "client_list",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_wall_id"],
            ["bw_business_wall.id"],
            name=op.f("fk_bw_bw_content_business_wall_id_bw_business_wall"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_bw_content")),
        sa.UniqueConstraint("business_wall_id"),
    )
    op.create_table(
        "bw_partnership",
        sa.Column(
            "business_wall_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("partner_org_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("invitation_message", sa.Text(), nullable=False),
        sa.Column(
            "invited_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "accepted_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "rejected_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "revoked_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "contract_start_date",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "contract_end_date",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_wall_id"],
            ["bw_business_wall.id"],
            name=op.f("fk_bw_partnership_business_wall_id_bw_business_wall"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_partnership")),
    )
    op.create_table(
        "bw_role_assignment",
        sa.Column(
            "business_wall_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_type", sa.String(), nullable=False),
        sa.Column("invitation_status", sa.String(), nullable=False),
        sa.Column(
            "invited_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "accepted_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "rejected_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_wall_id"],
            ["bw_business_wall.id"],
            name=op.f("fk_bw_role_assignment_business_wall_id_bw_business_wall"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_role_assignment")),
    )
    op.create_table(
        "bw_subscription",
        sa.Column(
            "business_wall_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("pricing_field", sa.String(), nullable=False),
        sa.Column("pricing_tier", sa.String(), nullable=False),
        sa.Column("monthly_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("annual_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("billing_cycle", sa.String(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(), nullable=True),
        sa.Column(
            "started_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=True,
        ),
        sa.Column("billing_first_name", sa.String(), nullable=False),
        sa.Column("billing_last_name", sa.String(), nullable=False),
        sa.Column("billing_company", sa.String(), nullable=False),
        sa.Column("billing_address", sa.String(), nullable=False),
        sa.Column("billing_city", sa.String(), nullable=False),
        sa.Column("billing_zip_code", sa.String(), nullable=False),
        sa.Column("billing_country", sa.String(), nullable=False),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_wall_id"],
            ["bw_business_wall.id"],
            name=op.f("fk_bw_subscription_business_wall_id_bw_business_wall"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_subscription")),
    )
    op.create_table(
        "bw_role_permission",
        sa.Column(
            "role_assignment_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("permission_type", sa.String(), nullable=False),
        sa.Column("is_granted", sa.Boolean(), nullable=False),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["bw_role_assignment.id"],
            name=op.f("fk_bw_role_permission_role_assignment_id_bw_role_assignment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bw_role_permission")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bw_role_permission")
    op.drop_table("bw_subscription")
    op.drop_table("bw_role_assignment")
    op.drop_table("bw_partnership")
    op.drop_table("bw_bw_content")
    op.drop_table("bw_business_wall")
    # ### end Alembic commands ###
