"""add JobOffer fields

Revision ID: 4a750af07df4
Revises: 28743aebde64
Create Date: 2026-07-28 16:30:01.418313

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a750af07df4"
down_revision = "28743aebde64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mkp_job_offer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("domain_studient", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column("domain_pro", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column(
                "type_emploi_pro_studient",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_emploi_pro_journaliste",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "competence_journalisme",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_emploi_pro_communicant",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "competence_relation_presse",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_emploi_pro_innovation",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column(
                "competence_innovation",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(
            sa.Column("niveau_etude", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column("matiere_etudiee", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column("langues", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column("ending_date", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("partial_time", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "remote_partial_time",
                sa.Boolean(),
                nullable=False,
                server_default="false",
            )
        )
        batch_op.add_column(
            sa.Column(
                "remote_full_time",
                sa.Boolean(),
                nullable=False,
                server_default="false",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mkp_job_offer", schema=None) as batch_op:
        batch_op.drop_column("remote_full_time")
        batch_op.drop_column("remote_partial_time")
        batch_op.drop_column("partial_time")
        batch_op.drop_column("ending_date")
        batch_op.drop_column("langues")
        batch_op.drop_column("matiere_etudiee")
        batch_op.drop_column("niveau_etude")
        batch_op.drop_column("competence_innovation")
        batch_op.drop_column("type_emploi_pro_innovation")
        batch_op.drop_column("competence_relation_presse")
        batch_op.drop_column("type_emploi_pro_communicant")
        batch_op.drop_column("competence_journalisme")
        batch_op.drop_column("type_emploi_pro_journaliste")
        batch_op.drop_column("type_emploi_pro_studient")
        batch_op.drop_column("domain_pro")
        batch_op.drop_column("domain_studient")

    # ### end Alembic commands ###
