"""Stripe status in BW

Revision ID: 5ebabed60373
Revises: 217dc369b44c
Create Date: 2025-11-17 17:45:13.804271

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ebabed60373"
down_revision = "217dc369b44c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stripe_subscription_status", sa.String(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crp_organisation", schema=None) as batch_op:
        batch_op.drop_column("stripe_subscription_status")
    # ### end Alembic commands ###
