"""add BusinessWall fields

Revision ID: 643c84a670aa
Revises: 7923cc2f1526
Create Date: 2026-02-27 15:32:25.815041

"""

from __future__ import annotations

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "643c84a670aa"
down_revision = "7923cc2f1526"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        # Nullable columns (no default needed)
        batch_op.add_column(
            sa.Column(
                "logo_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "cover_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("siren", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("tva", sa.String(), nullable=True))

        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum(
                    "AUTO",
                    "MEDIA",
                    "AGENCY",
                    "COM",
                    "OTHER",
                    name="organisationtypeenum",
                ),
                nullable=False,
                server_default="AUTO",
            )
        )

        batch_op.add_column(
            sa.Column("name_entity", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("agrement", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("name_press", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("clients", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("name_official", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("name_group", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "name_institution", sa.String(), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "positionnement_editorial",
                sa.String(),
                nullable=False,
                server_default="",
            )
        )
        batch_op.add_column(
            sa.Column("audience_cible", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("periodicite", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("taille_orga", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("tel_standard", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("postal_address", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("pays_zip_ville", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "pays_zip_ville_detail", sa.String(), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column("geolocalisation", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("site_url", sa.String(), nullable=False, server_default="")
        )

        batch_op.add_column(
            sa.Column(
                "type_presse_et_media",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_entreprise_media",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "type_agence_rp",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite_medias",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite_medias_detail",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite_rp",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite_rp_detail",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "secteurs_activite_detail",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_political",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_economics",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "interest_association",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )

        batch_op.create_index(
            batch_op.f("ix_bw_business_wall_type"), ["type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_business_wall_type"))
        batch_op.drop_column("site_url")
        batch_op.drop_column("geolocalisation")
        batch_op.drop_column("pays_zip_ville_detail")
        batch_op.drop_column("pays_zip_ville")
        batch_op.drop_column("postal_address")
        batch_op.drop_column("tel_standard")
        batch_op.drop_column("interest_association")
        batch_op.drop_column("interest_economics")
        batch_op.drop_column("interest_political")
        batch_op.drop_column("taille_orga")
        batch_op.drop_column("secteurs_activite_detail")
        batch_op.drop_column("secteurs_activite")
        batch_op.drop_column("secteurs_activite_rp_detail")
        batch_op.drop_column("secteurs_activite_rp")
        batch_op.drop_column("secteurs_activite_medias_detail")
        batch_op.drop_column("secteurs_activite_medias")
        batch_op.drop_column("periodicite")
        batch_op.drop_column("audience_cible")
        batch_op.drop_column("positionnement_editorial")
        batch_op.drop_column("name_institution")
        batch_op.drop_column("name_group")
        batch_op.drop_column("name_official")
        batch_op.drop_column("clients")
        batch_op.drop_column("type_agence_rp")
        batch_op.drop_column("type_entreprise_media")
        batch_op.drop_column("type_presse_et_media")
        batch_op.drop_column("name_press")
        batch_op.drop_column("agrement")
        batch_op.drop_column("tva")
        batch_op.drop_column("siren")
        batch_op.drop_column("name_entity")
        batch_op.drop_column("type")
        batch_op.drop_column("cover_image")
        batch_op.drop_column("logo_image")

    # ### end Alembic commands ###
