"""empty message

Revision ID: 661469a4563e
Revises:
Create Date: 2025-05-16 08:53:55.069937

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "661469a4563e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crm_communique",
        sa.Column("chapo", sa.String(), nullable=False),
        sa.Column("contenu", sa.String(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="com_publicationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "embargoed_until",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "published_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "expired_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column("publisher_id", sa.BigInteger(), nullable=True),
        sa.Column("titre", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("geo_localisation", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["aut_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["crp_organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # with op.batch_alter_table("frt_content", schema=None) as batch_op:
    #     batch_op.alter_column(
    #         "status",
    #         existing_type=postgresql.ENUM(
    #             "DRAFT", "PUBLIC", "ARCHIVED", name="poststatus3"
    #         ),
    #         type_=sa.Enum("DRAFT", "PUBLIC", "ARCHIVED", name="poststatus"),
    #         existing_nullable=False,
    #     )
    #     batch_op.alter_column(
    #         "publisher_type",
    #         existing_type=postgresql.ENUM("AGENCY", "MEDIA", name="publishertype2"),
    #         type_=sa.Enum("AGENCY", "MEDIA", name="publishertype"),
    #         existing_nullable=False,
    #     )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column(
            "publisher_type",
            existing_type=sa.Enum("AGENCY", "MEDIA", name="publishertype"),
            type_=postgresql.ENUM("AGENCY", "MEDIA", name="publishertype2"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("DRAFT", "PUBLIC", "ARCHIVED", name="poststatus"),
            type_=postgresql.ENUM("DRAFT", "PUBLIC", "ARCHIVED", name="poststatus3"),
            existing_nullable=False,
        )

    op.drop_table("crm_communique")
    # ### end Alembic commands ###
