"""empty message

Revision ID: 66eb37fc43e6
Revises: 529e8a4d26cc
Create Date: 2025-09-19 08:09:25.584272

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66eb37fc43e6'
down_revision = '529e8a4d26cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nrm_article', schema=None) as batch_op:
        batch_op.drop_column('date_paiement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nrm_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_paiement', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
