"""add field payer_is_owner to BusinessWall

Revision ID: 6aff299b1af9
Revises: a050669bd825
Create Date: 2026-02-16 15:05:44.360183

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aff299b1af9'
down_revision = 'a050669bd825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_is_owner', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.drop_column('payer_is_owner')

    # ### end Alembic commands ###
