"""empty message

Revision ID: 6cebca834ff7
Revises:
Create Date: 2025-03-21 07:46:37.026590

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "6cebca834ff7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crm_communique",
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PRIVATE",
                "PENDING",
                "PUBLIC",
                "REJECTED",
                "EXPIRED",
                "ARCHIVED",
                "DELETED",
                name="crm_publicationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "embargoed_until",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "published_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "expired_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column("publisher_id", sa.BigInteger(), nullable=False),
        sa.Column("titre", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("geo_localisation", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["aut_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["crp_organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("kyc_profile", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("kyc_tmp_blob", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # with op.batch_alter_table('wir_article', schema=None) as batch_op:
    #     batch_op.alter_column('newsroom_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('wir_article', schema=None) as batch_op:
    #     batch_op.alter_column('newsroom_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=False)

    with op.batch_alter_table("kyc_tmp_blob", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("kyc_profile", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.drop_table("crm_communique")
    # ### end Alembic commands ###
