"""index tax_taxonomy on taxonomy_name

Every taxonomy read filters on `taxonomy_name` and orders by
`(seq, name)`. Without this index Postgres sequentially scans the whole
table — 19k rows discarded to return 150 — on every form render.

Hand-written rather than autogenerated: the autogenerate picked up
unrelated drift, including a column drop on `evt_event_post`. Only the
index belongs here.

Revision ID: 6f5fd5c0d443
Revises: c5d6e7f8a9b0
Create Date: 2026-09-03 08:09:04.604972

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f5fd5c0d443"
down_revision = "c5d6e7f8a9b0"
branch_labels = None
depends_on = None

INDEX_NAME = "ix_tax_taxonomy_name_seq"


def upgrade():
    op.create_index(
        INDEX_NAME, "tax_taxonomy", ["taxonomy_name", "seq", "name"], unique=False
    )


def downgrade():
    op.drop_index(INDEX_NAME, table_name="tax_taxonomy")
