"""Partnership reference by BW.id

Revision ID: 7923cc2f1526
Revises: 7ebcd6bbba1c
Create Date: 2026-02-24 17:11:18.167316

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7923cc2f1526'
down_revision = '7ebcd6bbba1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('bw_partnership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_bw_id', sa.String(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE bw_partnership SET partner_bw_id = '' WHERE partner_bw_id IS NULL")

    with op.batch_alter_table('bw_partnership', schema=None) as batch_op:
        batch_op.alter_column('partner_bw_id', nullable=False)
        batch_op.drop_column('partner_org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('bw_partnership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_org_id', sa.BIGINT(), autoincrement=False, nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE bw_partnership SET partner_org_id = 0 WHERE partner_org_id IS NULL")

    with op.batch_alter_table('bw_partnership', schema=None) as batch_op:
        batch_op.alter_column('partner_org_id', nullable=False)
        batch_op.drop_column('partner_bw_id')

    # ### end Alembic commands ###
