"""add BWImage

Revision ID: 7cbe10b7736c
Revises: ce199be6ef00
Create Date: 2026-03-25 10:58:56.936817
"""

from __future__ import annotations

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cbe10b7736c"
down_revision = "ce199be6ef00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bw_image",
        sa.Column(
            "content",
            advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
            nullable=True,
        ),
        sa.Column(
            "business_wall_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("caption", sa.String(), nullable=False),
        sa.Column("copyright", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_wall_id"], ["bw_business_wall.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("bw_image")
    # ### end Alembic commands ###
