"""add bw ame

Revision ID: 7ebcd6bbba1c
Revises: 6aff299b1af9
Create Date: 2026-02-24 16:26:45.765921

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ebcd6bbba1c'
down_revision = '6aff299b1af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
