"""Add RDV fields to ContactAvisEnquete

Revision ID: 87fe4ec6c198
Revises: 0dffbb0384b6
Create Date: 2025-11-14 12:40:24.480081

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87fe4ec6c198'
down_revision = '0dffbb0384b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    rdvtype = postgresql.ENUM('PHONE', 'VIDEO', 'F2F', name='rdvtype')
    rdvtype.create(op.get_bind(), checkfirst=True)

    rdvstatus = postgresql.ENUM('NO_RDV', 'PROPOSED', 'ACCEPTED', 'CONFIRMED', name='rdvstatus')
    rdvstatus.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('nrm_contact_avis_enquete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rdv_type', sa.Enum('PHONE', 'VIDEO', 'F2F', name='rdvtype'), nullable=True))
        batch_op.add_column(sa.Column('rdv_status', sa.Enum('NO_RDV', 'PROPOSED', 'ACCEPTED', 'CONFIRMED', name='rdvstatus'), nullable=False))
        batch_op.add_column(sa.Column('proposed_slots', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('rdv_phone', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rdv_video_link', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rdv_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rdv_notes_journaliste', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rdv_notes_expert', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nrm_contact_avis_enquete', schema=None) as batch_op:
        batch_op.drop_column('rdv_notes_expert')
        batch_op.drop_column('rdv_notes_journaliste')
        batch_op.drop_column('rdv_address')
        batch_op.drop_column('rdv_video_link')
        batch_op.drop_column('rdv_phone')
        batch_op.drop_column('proposed_slots')
        batch_op.drop_column('rdv_status')
        batch_op.drop_column('rdv_type')

    # Drop enum types
    rdvstatus = postgresql.ENUM(name='rdvstatus')
    rdvstatus.drop(op.get_bind(), checkfirst=True)

    rdvtype = postgresql.ENUM(name='rdvtype')
    rdvtype.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
