"""add ComImage.content column

Revision ID: 8802f7a4880a
Revises: 5ebabed60373
Create Date: 2025-11-24 16:05:25.269833

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8802f7a4880a"
down_revision = "5ebabed60373"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crm_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=False)
        )
        op.execute(sa.text("DELETE FROM crm_image WHERE communique_id IS NOT NULL"))
        batch_op.drop_column("blob_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crm_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blob_id", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("content")
    # ### end Alembic commands ###
