"""add field BusinessWall.presentation

Revision ID: 888ac4f01dcb
Revises: 5b329ba8953d
Create Date: 2026-08-04 10:17:26.425722

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "888ac4f01dcb"
down_revision = "5b329ba8953d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("presentation", sa.String(), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("presentation")

    # ### end Alembic commands ###
