"""add column User.photo_image

Revision ID: 8b0da77a7479
Revises: 2d226d278d3b
Create Date: 2025-11-26 16:04:59.563395

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b0da77a7479"
down_revision = "2d226d278d3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "photo_image",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aut_user", schema=None) as batch_op:
        batch_op.drop_column("photo_image")
    # ### end Alembic commands ###
