"""Add publisher_id to newsroom models

Revision ID: 8c401584035a
Revises: cdebc0d544aa
Create Date: 2026-05-25 14:32:59.430400

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "8c401584035a"
down_revision = "cdebc0d544aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("evt_event_post_publisher_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("nrm_avis_enquete", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])

    with op.batch_alter_table("nrm_commande", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])

    with op.batch_alter_table("nrm_sujet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nrm_sujet", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("nrm_commande", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("nrm_avis_enquete", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("publisher_id", sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("evt_event_post_publisher_id_fkey"),
            "crp_organisation",
            ["publisher_id"],
            ["id"],
        )

    # ### end Alembic commands ###
