"""Add publisher_id to newsroom models

Revision ID: 8c401584035a
Revises: cdebc0d544aa
Create Date: 2026-05-25 14:32:59.430400

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c401584035a"
down_revision = "cdebc0d544aa"
branch_labels = None
depends_on = None


def upgrade():
    # Adjusted from the autogenerated version : the original migration
    # also DROPPED `evt_event_post.publisher_id`, but that column is
    # still needed by `EventPost` (the `Publishable` mixin in
    # `app/models/content/mixins.py` declares it via `@declared_attr`).
    # The autogenerate diff fired because of a transient state during
    # Jerome's mixin refactor — keep the event column untouched here.
    with op.batch_alter_table("nrm_avis_enquete", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])

    with op.batch_alter_table("nrm_commande", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])

    with op.batch_alter_table("nrm_sujet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("publisher_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, "crp_organisation", ["publisher_id"], ["id"])


def downgrade():
    with op.batch_alter_table("nrm_sujet", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("nrm_commande", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")

    with op.batch_alter_table("nrm_avis_enquete", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("publisher_id")
