"""Add + back-fill EventPost.publisher_id from Event.publisher_id

Bugs #0135 and #0138: until commit 8a50dbd5 the events receiver did
not propagate publisher_id from the source Event onto the publicly-
listed EventPost. Real events created before the fix sit in production
with EventPost.publisher_id = NULL (where the column exists at all),
which keeps them invisible on the client's Business Wall (the BW
query filters on publisher_id == org.id).

Two-step migration:

1. Ensure the column exists on `evt_event_post`. The `Publishable`
   mixin (`app.models.content.mixins`) declares `publisher_id` as a
   `@declared_attr`, but the column was never explicitly added to
   `evt_event_post` by an autogenerated migration — local SQLite
   created it via `db.create_all()` but the production PostgreSQL
   schema never got it. `ADD COLUMN IF NOT EXISTS` so the migration
   is a no-op on databases where local autogenerate had already
   added the column.

2. Back-fill `publisher_id` from `evr_event.publisher_id` joined via
   `evt_event_post.eventroom_id = evr_event.id`.

Idempotent — re-running is a no-op since the column exists and the
second pass finds nothing to back-fill.

Revision ID: 9198ede3fe32
Revises: fe9ab2b94cf4
Create Date: 2026-05-13
"""

from __future__ import annotations

from alembic import op

revision = "9198ede3fe32"
down_revision = "fe9ab2b94cf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: ensure the column exists. IF NOT EXISTS is PostgreSQL-
    # specific but matches the production target; on SQLite this DDL
    # path is not exercised because tests use `db.create_all()`.
    op.execute(
        """
        ALTER TABLE evt_event_post
          ADD COLUMN IF NOT EXISTS publisher_id BIGINT
          REFERENCES crp_organisation(id)
        """
    )

    # Step 2: back-fill from the eventroom Event.
    op.execute(
        """
        UPDATE evt_event_post AS p
        SET publisher_id = e.publisher_id
        FROM evr_event AS e
        WHERE p.eventroom_id = e.id
          AND p.publisher_id IS NULL
          AND e.publisher_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # Drop the column we may have added. `IF EXISTS` to stay idempotent
    # on databases where step 1 was a no-op above (column was already
    # present and we'd otherwise drop someone else's column twice).
    op.execute(
        "ALTER TABLE evt_event_post DROP COLUMN IF EXISTS publisher_id"
    )
