"""change address fiels of Article, Communique

Revision ID: 968180489837
Revises: 1616d72057d1
Create Date: 2025-10-21 16:11:15.095934

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "968180489837"
down_revision = "1616d72057d1"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add columns as NULLABLE
    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        # NOTE: nullable=True (default) for temporary safety
        batch_op.add_column(sa.Column("address", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pays_zip_ville", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("pays_zip_ville_detail", sa.String(), nullable=True)
        )
    # Step 2: Update existing rows with the default value
    op.execute("UPDATE crm_communique SET address = '' WHERE address IS NULL")
    op.execute(
        "UPDATE crm_communique SET pays_zip_ville = '' WHERE pays_zip_ville IS NULL"
    )
    op.execute(
        "UPDATE crm_communique SET pays_zip_ville_detail = '' WHERE pays_zip_ville_detail IS NULL"
    )
    # Step 3: Set the columns to NOT NULL
    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        batch_op.alter_column("address", existing_type=sa.String(), nullable=False)
        batch_op.alter_column(
            "pays_zip_ville", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "pays_zip_ville_detail", existing_type=sa.String(), nullable=False
        )
    # ###################
    # Step 1: Add columns as NULLABLE
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pays_zip_ville", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("pays_zip_ville_detail", sa.String(), nullable=True)
        )
    # Step 2: Update existing rows with the default value
    op.execute("UPDATE frt_content SET address = '' WHERE address IS NULL")
    op.execute(
        "UPDATE frt_content SET pays_zip_ville = '' WHERE pays_zip_ville IS NULL"
    )
    op.execute(
        "UPDATE frt_content SET pays_zip_ville_detail = '' WHERE pays_zip_ville_detail IS NULL"
    )
    # Step 3: Set the columns to NOT NULL
    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.alter_column("address", existing_type=sa.String(), nullable=False)
        batch_op.alter_column(
            "pays_zip_ville", existing_type=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "pays_zip_ville_detail", existing_type=sa.String(), nullable=False
        )
        # ###################
        # Step 1: Add column as NULLABLE
        with op.batch_alter_table("nrm_article", schema=None) as batch_op:
            batch_op.add_column(sa.Column("address", sa.String(), nullable=True))
        # Step 2: Update existing rows with the default value ("")
        op.execute("UPDATE nrm_article SET address = '' WHERE address IS NULL")
        # Step 3: Set the column to NOT NULL
        with op.batch_alter_table("nrm_article", schema=None) as batch_op:
            batch_op.alter_column("address", existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nrm_article", schema=None) as batch_op:
        batch_op.drop_column("address")

    with op.batch_alter_table("frt_content", schema=None) as batch_op:
        batch_op.drop_column("pays_zip_ville_detail")
        batch_op.drop_column("pays_zip_ville")
        batch_op.drop_column("address")

    with op.batch_alter_table("crm_communique", schema=None) as batch_op:
        batch_op.drop_column("pays_zip_ville_detail")
        batch_op.drop_column("pays_zip_ville")
        batch_op.drop_column("address")
    # ### end Alembic commands ###
