"""empty message

Revision ID: 97ca0a7dd491
Revises: c15af08636a4
Create Date: 2026-04-22 08:51:16.581996

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97ca0a7dd491'
down_revision = 'c15af08636a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_article_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sqlalchemy_utils.types.arrow.ArrowType(timezone=True), nullable=False))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_wire_article_purchase_owner_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_article_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_wire_article_purchase_owner_id'), ['owner_id'], unique=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
