"""add fields and foreign keys to BusinessWall

Revision ID: a050669bd825
Revises: 18fc5059a3ae
Create Date: 2026-02-16 14:49:13.070115

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a050669bd825'
down_revision = '18fc5059a3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        # Add columns with server_default to handle existing rows
        batch_op.add_column(sa.Column('payer_first_name', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('payer_last_name', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('payer_service', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('payer_email', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('payer_phone', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('payer_address', sa.String(), server_default='', nullable=False))
        batch_op.create_foreign_key('fk_bw_business_wall_payer_id', 'aut_user', ['payer_id'], ['id'])
        batch_op.create_foreign_key('fk_bw_business_wall_org_id', 'crp_organisation', ['organisation_id'], ['id'])
        batch_op.create_foreign_key('fk_bw_business_wall_owner_id', 'aut_user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bw_business_wall', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bw_business_wall_owner_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bw_business_wall_org_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bw_business_wall_payer_id', type_='foreignkey')
        batch_op.drop_column('payer_address')
        batch_op.drop_column('payer_phone')
        batch_op.drop_column('payer_email')
        batch_op.drop_column('payer_service')
        batch_op.drop_column('payer_last_name')
        batch_op.drop_column('payer_first_name')

    # ### end Alembic commands ###
