"""commande.date_paiement becomes nullable

Bug #0343. A rédac chef commissions an article knowing the bouclage and
the publication dates, and *not* the payment date — « c'est un problème
récurrent dans notre profession ». The field left `CommandeForm`; the
column stays so the commandes that already carry a date keep it.

Hand-written rather than autogenerated: autogenerate picks up unrelated
drift on this schema (see 6f5fd5c0d443). Only this column belongs here.

The downgrade cannot restore NOT NULL blindly — rows commissioned after
this migration have no payment date, and there is none to invent. It
fills them from `date_parution_prevue`, which is what `sujet_accept`
used to do for the same reason, and refuses if that is null too.

Revision ID: a2c4e6b8d0f1
Revises: 6f5fd5c0d443
Create Date: 2026-09-08 22:10:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2c4e6b8d0f1"
down_revision = "6f5fd5c0d443"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column(
        "nrm_commande",
        "date_paiement",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )


def downgrade():
    op.execute(
        "UPDATE nrm_commande "
        "SET date_paiement = date_parution_prevue "
        "WHERE date_paiement IS NULL"
    )
    remaining = (
        op.get_bind()
        .execute(
            sa.text("SELECT count(*) FROM nrm_commande WHERE date_paiement IS NULL")
        )
        .scalar()
    )
    if remaining:
        msg = (
            f"{remaining} commande(s) have neither a payment date nor a "
            "publication date to fall back on. Fill them before downgrading."
        )
        raise RuntimeError(msg)
    op.alter_column(
        "nrm_commande",
        "date_paiement",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
