"""empty message

Revision ID: a3d7e2226722
Revises:
Create Date: 2024-12-12 22:13:36.532448

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "a3d7e2226722"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kyc_profile", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("kyc_tmp_blob", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("wir_article", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_updated_at",
                sqlalchemy_utils.types.arrow.ArrowType(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wir_article", schema=None) as batch_op:
        batch_op.drop_column("last_updated_at")

    with op.batch_alter_table("kyc_tmp_blob", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("kyc_profile", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
