"""add field JobOffer.statut

Revision ID: a5bd49ba521e
Revises: f2312489c5eb
Create Date: 2026-07-24 16:13:12.149109

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a5bd49ba521e"
down_revision = "f2312489c5eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mkp_job_offer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("statut", sa.String(), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mkp_job_offer", schema=None) as batch_op:
        batch_op.drop_column("statut")

    # ### end Alembic commands ###
