"""empty message

Revision ID: a674e53fdff0
Revises: 46da924e53a0
Create Date: 2025-04-04 10:58:12.785669

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "a674e53fdff0"
down_revision = "46da924e53a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wir_article", schema=None) as batch_op:
        batch_op.alter_column("newsroom_id", existing_type=sa.BIGINT(), nullable=False)

    # ### end Alembic commands ###
