"""empty message

Revision ID: a8d39d5affe5
Revises: d2a6c00ea6c2
Create Date: 2025-05-09 08:52:22.677397

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d39d5affe5'
down_revision = 'd2a6c00ea6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.Enum('DRAFT', 'PRIVATE', 'PENDING', 'PUBLIC', 'REJECTED', 'EXPIRED', 'ARCHIVED', 'DELETED', name='publicationstatus'), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('DRAFT', 'PRIVATE', 'PENDING', 'PUBLIC', 'REJECTED', 'EXPIRED', 'ARCHIVED', 'DELETED', name='publicationstatus'), autoincrement=False, nullable=False))
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
