"""add EmailLog table

Revision ID: ad80dabfbc9a
Revises: 10aea8b9a3b4
Create Date: 2025-12-05 11:26:06.865571

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ad80dabfbc9a"
down_revision = "10aea8b9a3b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_log",
        sa.Column("recipient_email", sa.String(), nullable=False),
        sa.Column(
            "sent_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            sqlalchemy_utils.types.arrow.ArrowType(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_log_recipient_email"),
            ["recipient_email"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("email_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_log_recipient_email"))

    op.drop_table("email_log")
    # ### end Alembic commands ###
