"""empty message

Revision ID: b0172ee573b2
Revises: 8802f7a4880a
Create Date: 2025-11-24 17:15:14.504905

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0172ee573b2"
down_revision = "8802f7a4880a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crm_image", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=advanced_alchemy.types.file_object.data_type.StoredObject(
                backend="local"
            ),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crm_image", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=advanced_alchemy.types.file_object.data_type.StoredObject(
                backend="local"
            ),
            type_=postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        )
    # ### end Alembic commands ###
