"""organisation attributes

Revision ID: beb6712180e4
Revises: 01dd37023542
Create Date: 2026-03-19 15:21:17.789096

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'beb6712180e4'
down_revision = '01dd37023542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bw_active', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bw_id', sa.Uuid(), nullable=True))

    # Populate bw_active and bw_id from active BusinessWalls
    op.execute("""
        UPDATE crp_organisation
        SET
            bw_active = bw.bw_type,
            bw_id = bw.id
        FROM bw_business_wall bw
        WHERE
            bw.organisation_id = crp_organisation.id
            AND bw.status = 'active'
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('crp_organisation', schema=None) as batch_op:
        batch_op.drop_column('bw_id')
        batch_op.drop_column('bw_active')

    # ### end Alembic commands ###
