"""use S3 for article image

Revision ID: cb2670cb8cbe
Revises: b0172ee573b2
Create Date: 2025-11-25 15:49:04.438480

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb2670cb8cbe"
down_revision = "b0172ee573b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("nrm_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "content",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        op.execute(sa.text("DELETE FROM nrm_image WHERE article_id IS NOT NULL"))
        batch_op.drop_column("blob_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nrm_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blob_id", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("content")
    # ### end Alembic commands ###
