"""add column profile to Promotion

Revision ID: cc0da390b540
Revises: 249c5b1dbf2b
Create Date: 2025-11-05 17:06:19.340106

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc0da390b540"
down_revision = "249c5b1dbf2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    profile_enum = sa.Enum(
        "PM_DIR",
        "PM_JR_CP_SAL",
        "PM_JR_PIG",
        "PM_JR_CP_ME",
        "PM_JR_ME",
        "PM_DIR_INST",
        "PM_JR_INST",
        "PM_DIR_SYND",
        "PR_DIR",
        "PR_CS",
        "PR_CS_IND",
        "PR_DIR_COM",
        "PR_CS_COM",
        "XP_DIR_ANY",
        "XP_ANY",
        "XP_PR",
        "XP_IND",
        "XP_DIR_SU",
        "XP_INV_PUB",
        "XP_DIR_EVT",
        "TP_DIR_ORG",
        "TR_CS_ORG",
        "TR_CS_ORG_PR",
        "TR_CS_ORG_IND",
        "TR_DIR_SU_ORG",
        "TR_INV_ORG",
        "TR_DIR_POLE",
        "AC_DIR",
        "AC_DIR_JR",
        "AC_ENS",
        "AC_DOC",
        "AC_ST",
        "AC_ST_ENT",
        name="adm_profileenum",
    )
    profile_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table("adm_promotion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile", profile_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE adm_promotion DROP COLUMN IF EXISTS profile;")

    # ### end Alembic commands ###
