"""add selected_bw_id to user

Revision ID: cdebc0d544aa
Revises: b248311c63d7
Create Date: 2026-05-22 15:26:51.358504

"""
from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = 'cdebc0d544aa'
down_revision = 'b248311c63d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aut_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_bw_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aut_user', schema=None) as batch_op:
        batch_op.drop_column('selected_bw_id')

    # ### end Alembic commands ###
