"""BW images copyright

Revision ID: ce199be6ef00
Revises: 17850c9cf4a6
Create Date: 2026-03-24 11:40:43.345681

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce199be6ef00"
down_revision = "17850c9cf4a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("logo_image_copyright", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cover_image_copyright", sa.String(), nullable=True)
        )

    op.execute("UPDATE bw_business_wall SET logo_image_copyright = ''")
    op.execute("UPDATE bw_business_wall SET cover_image_copyright = ''")
    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.alter_column("logo_image_copyright", nullable=False)
        batch_op.alter_column("cover_image_copyright", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bw_business_wall", schema=None) as batch_op:
        batch_op.drop_column("cover_image_copyright")
        batch_op.drop_column("logo_image_copyright")

    # ### end Alembic commands ###
