"""empty message

Revision ID: d2a6c00ea6c2
Revises: 239dbcc5baef
Create Date: 2025-05-09 08:45:28.655152

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'd2a6c00ea6c2'
down_revision = '239dbcc5baef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.alter_column('publisher_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_communique', schema=None) as batch_op:
        batch_op.alter_column('publisher_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
