"""Events fields location renamed

Revision ID: d5e8e4552f1e
Revises: 968180489837
Create Date: 2025-10-22 11:43:25.529990

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d5e8e4552f1e"
down_revision = "968180489837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.drop_column("location")

    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(), nullable=True))

    op.execute("UPDATE evt_event_post SET address = '' WHERE address IS NULL")

    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.alter_column("address", existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("evt_event_post", schema=None) as batch_op:
        batch_op.drop_column("address")

    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(), nullable=True))
    op.execute("UPDATE evr_event SET location = '' WHERE location IS NULL")
    with op.batch_alter_table("evr_event", schema=None) as batch_op:
        batch_op.alter_column("location", existing_type=sa.String(), nullable=False)
