"""drop old kyc_tmp_blob table

Revision ID: d7ff7af33908
Revises: d3369b39a653
Create Date: 2026-02-11 10:10:23.033901

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7ff7af33908"
down_revision = "d3369b39a653"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kyc_tmp_blob")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kyc_tmp_blob",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uuid", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("kyc_tmp_blob_pkey")),
    )
    # ### end Alembic commands ###
