"""empty message

Revision ID: ec4225d73a10
Revises: 661469a4563e
Create Date: 2025-06-12 09:37:40.579894

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'ec4225d73a10'
down_revision = '661469a4563e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evr_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.drop_column('topic')
        batch_op.drop_column('genre')
        batch_op.drop_column('geo_localisation')
        batch_op.drop_column('section')

    with op.batch_alter_table('kyc_profile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('kyc_tmp_blob', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_tmp_blob', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('kyc_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('evr_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('geo_localisation', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('address')
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
