"""use S3 for event image

Revision ID: f41e8fa6e55b
Revises: cb2670cb8cbe
Create Date: 2025-11-25 16:47:05.034319

"""

import advanced_alchemy
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f41e8fa6e55b"
down_revision = "cb2670cb8cbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evr_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "content",
                advanced_alchemy.types.file_object.data_type.StoredObject(backend="s3"),
                nullable=True,
            )
        )
        op.execute(sa.text("DELETE FROM evr_image WHERE event_id IS NOT NULL"))
        batch_op.drop_column("blob_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evr_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blob_id", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("content")
    # ### end Alembic commands ###
