"""adapt EventPost fields to Event

Revision ID: f76fe3d57b92
Revises: 0fb901d6eef6
Create Date: 2025-10-14 17:11:44.516350

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f76fe3d57b92"
down_revision = "0fb901d6eef6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pays_zip_ville", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("pays_zip_ville_detail", sa.String(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cnt_base", schema=None) as batch_op:
        batch_op.drop_column("pays_zip_ville_detail")
        batch_op.drop_column("pays_zip_ville")

    # ### end Alembic commands ###
