# Copyright (c) 2021-2026, Abilian SAS & TCA
#
# SPDX-License-Identifier: AGPL-3.0-only

"""Unit tests for `CommuniqueForm` validation in
`app.modules.wip.crud.cbvs._forms`.

WTForms validation runs in-process — no DB, no HTTP — so it lands
naturally in a_unit. The form is auto-generated (see the
"Autogenerated. DO NOT EDIT." banner in the source) and drives the
press-release (comroom) CRUD flow ; pinning the validators here
catches three classes of silent regression :

1. **Tightening** : a future « add InputRequired to chapo » that
   breaks legitimate communiqués published without a sub-headline.
2. **Loosening** : a future « accidentally remove InputRequired from
   titre / contenu » that lets nameless or empty press releases
   ship into the comroom listings.
3. **Choice drift** : a vocabulary key getting renamed without the
   form being re-generated, so the dropdown silently refuses every
   value the JS client posts. The form binds `genre` to the
   `genre-com` vocab (not `genre` — that one is used by the article
   form). That naming subtlety is exactly the kind of thing a global
   rename misses.

Note : the four `RichSelectField`s (`sector`, `section`, `topic`,
`genre`) load choices dynamically from
`app.flask.forms.get_choices`, which reads from the `tax_taxonomy`
DB table. In the a_unit layer that table is empty, so we stub the
field's `choices` list before validating. That keeps these tests
independent of vocabulary seeding and lets us pin the underlying
contract (« value must be a known choice ») deterministically.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from werkzeug.datastructures import ImmutableMultiDict

from app.modules.wip.crud.cbvs._forms import CommuniqueForm

if TYPE_CHECKING:
    from flask import Flask


# Stub values used to populate the four RichSelectField `choices`
# in `_make_form`. They have no semantic meaning — they only need to
# be stable enough to round-trip through SelectField's pre-validation.
_STUB_SECTOR = "STUB-SECTOR"
_STUB_SECTION = "STUB-SECTION"
_STUB_TOPIC = "STUB-TOPIC"
_STUB_GENRE = "STUB-GENRE"

_GOOD_TITRE = "Communiqué de presse"
_GOOD_CONTENU = "Le corps du communiqué"
_GOOD_DATETIME = "2025-01-15T10:30"


def _baseline_payload() -> dict[str, str]:
    """Smallest dict that passes validation against the stubbed
    choices set in `_make_form`. Tests override individual keys to
    exercise specific branches without re-typing the full dict."""
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "sector": _STUB_SECTOR,
        "section": _STUB_SECTION,
        "topic": _STUB_TOPIC,
        "genre": _STUB_GENRE,
    }


def _make_form(app: Flask, data: dict | None = None) -> CommuniqueForm:
    """Instantiate `CommuniqueForm` against a fake POST payload.
    Encapsulates : test_request_context, ImmutableMultiDict wrapping,
    and stubbing of the four RichSelectField `choices` lists (the
    production code populates them from the taxonomy cache ; we
    override with a single-entry list so SelectField pre-validation
    can pass without a seeded DB)."""
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = CommuniqueForm(payload)
        form.sector.choices = [(_STUB_SECTOR, _STUB_SECTOR)]
        form.section.choices = [(_STUB_SECTION, _STUB_SECTION)]
        form.topic.choices = [(_STUB_TOPIC, _STUB_TOPIC)]
        form.genre.choices = [(_STUB_GENRE, _STUB_GENRE)]
        return form


class TestRequiredFields:
    """Pin every InputRequired the source declares. A future
    refactor that drops one of these would silently let half-built
    communiqués ship to the comroom listings."""

    def test_baseline_payload_validates(self, app: Flask):
        """Sanity : the minimal-good payload validates. Anchors the
        rest of the suite — if this breaks, every other test is
        suspect."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize(
        "field_name",
        ["titre", "contenu", "sector", "section", "topic", "genre"],
    )
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        """Each declared-required field, when blanked, must surface
        an error on *that* field. Catches « accidentally removed
        InputRequired » regressions without enumerating per-field
        boilerplate."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize(
        "field_name",
        ["titre", "contenu", "sector", "section", "topic", "genre"],
    )
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        """Same as blank, but the key isn't even present in the POST.
        WTForms treats missing-key and blank-value identically for
        InputRequired ; pin that contract so a future SelectField
        switch doesn't silently swallow missing keys."""
        payload = _baseline_payload()
        payload.pop(field_name)
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestOptionalFields:
    """Fields without InputRequired must pass when empty. Pin the
    contract so a future « add InputRequired to chapo » doesn't
    silently reject every press release submitted without a
    sub-headline."""

    def test_chapo_optional(self, app: Flask):
        """`chapo` (the sub-headline) is the only optional text
        field. An empty value must NOT block the form."""
        payload = _baseline_payload()
        payload["chapo"] = ""
        form = _make_form(app, payload)
        assert form.validate(), f"Empty chapo should validate, errors={form.errors}"

    def test_chapo_long_accepted(self, app: Flask):
        """No length cap on the sub-headline. Pin so a future
        « maxlength=200 » doesn't silently truncate long-form
        chapôs."""
        payload = _baseline_payload()
        payload["chapo"] = "x" * 5000
        form = _make_form(app, payload)
        assert form.validate(), f"Long chapo should validate, errors={form.errors}"

    def test_pays_zip_ville_optional(self, app: Flask):
        """`pays_zip_ville` is a `CountrySelectField` with
        `validate_choice=False` (the choices list is loaded
        client-side by the tom-select widget, not by the server).
        Pin so a future « add InputRequired » regression that
        breaks every comroom POST is visible."""
        # Baseline omits pays_zip_ville → form must still validate.
        form = _make_form(app, _baseline_payload())
        assert form.validate()
        assert not form.pays_zip_ville.errors


class TestSelectFieldChoices:
    """RichSelectField wraps a strict SelectField : values must be in
    `choices`. Pin so a future `validate_choice=False` regression
    that lets bogus values reach the DB is caught."""

    @pytest.mark.parametrize(
        "field_name",
        ["sector", "section", "topic", "genre"],
    )
    def test_bogus_choice_rejected(self, app: Flask, field_name: str):
        """A value that's not in the (stubbed) vocabulary must
        surface a per-field error. Catches both « JS client sent a
        stale value » and « vocab key was renamed » regressions."""
        payload = _baseline_payload()
        payload[field_name] = "totally-not-a-real-choice"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors

    def test_pays_zip_ville_accepts_any_value(self, app: Flask):
        """`pays_zip_ville` was deliberately configured with
        `validate_choice=False` because the country list is
        rendered client-side. Pin so a future « tighten validation »
        doesn't silently break the comroom POST path."""
        payload = _baseline_payload()
        payload["pays_zip_ville"] = "FR"  # not in the (empty) choices
        form = _make_form(app, payload)
        assert form.validate(), (
            f"pays_zip_ville must accept any string, errors={form.errors}"
        )

    def test_genre_uses_genre_com_vocabulary(self, app: Flask):
        """The `genre` field of `CommuniqueForm` binds to the
        `genre-com` vocab key (NOT `genre`, which is used by the
        article form). That subtlety is easy to miss in a global
        rename — pin it so we'd catch a silent regression."""
        # `RichSelectField` exposes the vocab key via the `key`
        # attribute set at construction time.
        form = _make_form(app, _baseline_payload())
        assert form.genre.key == "genre-com"


class TestDateTimeFields:
    """`embargoed_until` and `published_at` are `DateTimeField`s with
    the HTML5 datetime-local format. Pin parsing so a future widget
    swap doesn't silently break inbound requests, and pin that both
    are optional (the embargo via an explicit `Optional()`, the
    published_at via the absence of any validators)."""

    def test_embargoed_until_optional(self, app: Flask):
        """Empty `embargoed_until` must NOT surface a per-field
        error and `data` must be None (not a sentinel datetime)."""
        payload = _baseline_payload()
        payload["embargoed_until"] = ""
        form = _make_form(app, payload)
        assert form.validate()
        assert not form.embargoed_until.errors
        assert form.embargoed_until.data is None

    def test_published_at_missing_key_passes(self, app: Flask):
        """`published_at` has no declared validators at all (note
        the commented-out `Optional()` line in the source). A
        completely missing key in the POST must pass and parse to
        None. Pin this so a future « accidentally add InputRequired »
        is loud."""
        payload = _baseline_payload()
        payload.pop("published_at", None)
        form = _make_form(app, payload)
        assert form.validate(), f"Missing key should pass, errors={form.errors}"
        assert not form.published_at.errors
        assert form.published_at.data is None

    def test_published_at_empty_string_rejected(self, app: Flask):
        """Subtle but important : because `published_at` declares no
        `Optional()` validator, an *empty string* POST value (which
        is what HTML forms send for unfilled fields) is fed to the
        datetime parser and rejected as a parse error. The
        production view layer is expected to scrub empty strings
        before calling `form.validate()` — pin the quirk here so a
        future refactor that drops the scrubber is caught loudly
        instead of via mysterious end-user errors."""
        payload = _baseline_payload()
        payload["published_at"] = ""
        form = _make_form(app, payload)
        assert not form.validate()
        assert form.published_at.errors

    def test_embargoed_until_html5_format_accepted(self, app: Flask):
        """HTML5 datetime-local format (`YYYY-MM-DDTHH:MM`) is what
        the publish-form template emits. Pin so a future format
        swap is visible at the unit layer."""
        payload = _baseline_payload()
        payload["embargoed_until"] = _GOOD_DATETIME
        form = _make_form(app, payload)
        assert form.validate(), f"HTML5 dt should parse, errors={form.errors}"
        assert form.embargoed_until.data is not None

    def test_published_at_html5_format_accepted(self, app: Flask):
        payload = _baseline_payload()
        payload["published_at"] = _GOOD_DATETIME
        form = _make_form(app, payload)
        assert form.validate(), f"HTML5 dt should parse, errors={form.errors}"
        assert form.published_at.data is not None

    @pytest.mark.parametrize(
        "field_name",
        ["embargoed_until", "published_at"],
    )
    def test_garbage_datetime_rejected(self, app: Flask, field_name: str):
        """Non-parseable strings must surface a per-field error on
        both datetime fields. The two fields share the same
        underlying `DateTimeField` class but have different
        validators ; pin that both still report parse failures."""
        payload = _baseline_payload()
        payload[field_name] = "not-a-date"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestFormShape:
    """Lock the public field surface. The form has a published
    `Meta.groups` mapping that the rendering layer iterates — if a
    field is renamed without updating Meta, the template silently
    drops the field. These tests pin the shape."""

    def test_field_names_are_stable(self, app: Flask):
        """Pin the exact set of fields so a rename is loud, not
        silent. The list mirrors the source declaration."""
        form = _make_form(app, {})
        expected = {
            "titre",
            "chapo",
            "contenu",
            "sector",
            "section",
            "topic",
            "genre",
            "pays_zip_ville",
            "embargoed_until",
            "published_at",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_only_reference_real_fields(self, app: Flask):
        """Every name listed in `Meta.groups[*].fields` must
        correspond to an actual form field. Catches « renamed field
        but forgot to update Meta » before the template breaks."""
        form = _make_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in CommuniqueForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared fields: {declared}"
                )

    def test_meta_groups_expected_layout(self, app: Flask):
        """The four-group layout (headers / contenu / metadata /
        dates) is part of the rendered page contract. Pin it so a
        re-org is intentional and reviewed."""
        groups = CommuniqueForm.Meta.groups
        assert set(groups.keys()) == {"headers", "contenu", "metadata", "dates"}
        # pays_zip_ville renders last in metadata — see
        # test_form_layout.py for the rationale (bug 0124-A).
        assert groups["metadata"]["fields"][-1] == "pays_zip_ville"
        assert groups["dates"]["fields"] == ["embargoed_until", "published_at"]

    def test_defaults_when_unfilled(self, app: Flask):
        """An empty POST must yield None / empty-string defaults
        across all fields. Pin so a future « class-level default »
        addition doesn't silently fill DB columns with surprises."""
        form = _make_form(app, {})
        for name in ("titre", "chapo", "contenu"):
            assert not form[name].data, (
                f"{name} should default falsy, got {form[name].data!r}"
            )
        # Select fields default to None when the payload is empty.
        for name in ("sector", "section", "topic", "genre"):
            assert form[name].data is None
        # DateTime fields default to None — pin so a future
        # « default = datetime.utcnow » regression that silently
        # back-dates every draft is visible.
        for name in ("embargoed_until", "published_at"):
            assert form[name].data is None

    def test_country_field_dual_select_attributes(self, app: Flask):
        """`pays_zip_ville` is a `CountrySelectField`, which carries
        the second-input attributes (`name2`, `id2`, `label2`) used
        by the tom-select widget. Pin so a future template refactor
        that forgets to wire one of them is caught."""
        form = _make_form(app, {})
        assert form.pays_zip_ville.label.text == "Pays"
        assert form.pays_zip_ville.label2 == "Code postal et ville"
        assert form.pays_zip_ville.name2 == "pays_zip_ville_detail"
        assert form.pays_zip_ville.id2 == "pzv_detail"

    def test_select_render_widths(self, app: Flask):
        """The `render_kw['width']` values feed the renderer's grid
        — pin the widths so a future template refactor that drops
        the layout hint is visible. The widths mirror the source
        declaration : sector/topic span 6, section/genre span 3."""
        form = _make_form(app, {})
        assert form.sector.render_kw == {"width": 6}
        assert form.topic.render_kw == {"width": 6}
        assert form.section.render_kw == {"width": 3}
        assert form.genre.render_kw == {"width": 3}
