# Copyright (c) 2021-2026, Abilian SAS & TCA
#
# SPDX-License-Identifier: AGPL-3.0-only

"""Unit tests for `ArticleForm` validation in
`app.modules.wip.crud.cbvs._forms`.

WTForms validation runs in-process — no DB, no HTTP — so it lands
naturally in a_unit. The form is auto-generated (see the
"Autogenerated. DO NOT EDIT." banner in the source) and drives the
core newsroom CRUD flow ; pinning the validators here catches three
classes of silent regression :

1. **Tightening** : a future « add InputRequired to chapo » that
   breaks legitimate articles published without a sub-headline.
2. **Loosening** : a future « accidentally remove InputRequired from
   titre / contenu » that lets nameless or empty articles ship into
   the newsroom listings.
3. **Choice drift** : a vocabulary key getting renamed without the
   form being re-generated, so the dropdown silently refuses every
   value the JS client posts.

Note : `RichSelectField.choices` is dynamically loaded from
`app.flask.forms.get_choices`, which itself reads from
`app.settings.vocabularies`. Tests instantiate the form inside an
`app.test_request_context()` so those module-level vocabularies are
importable and SVCS / Flask globals are available.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from werkzeug.datastructures import ImmutableMultiDict

from app.modules.wip.crud.cbvs._forms import ArticleForm

if TYPE_CHECKING:
    from flask import Flask


# Minimal-valid payload (everything that is *required* set to a known
# good value). Tests override individual keys to exercise specific
# branches without re-typing the full dict every time.
_GOOD_TITRE = "Mon article"
_GOOD_CONTENU = "Le corps de l'article"
_GOOD_GENRE = "Actualité"
_GOOD_SECTION = "Autres"
_GOOD_TOPIC = "INFO GÉNÉ / Politique"
_GOOD_SECTOR = "POLITIQUE / Autres"
_GOOD_COPYRIGHT = "Tous droits réservés"
_GOOD_DATE = "2025-01-01T10:30"
_GOOD_MEDIA_ID = "1"


def _baseline_payload() -> dict[str, str]:
    """Smallest dict that passes validation (assuming `media_id`
    choices are populated externally — see `_make_form`)."""
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "genre": _GOOD_GENRE,
        "section": _GOOD_SECTION,
        "topic": _GOOD_TOPIC,
        "sector": _GOOD_SECTOR,
        "media_id": _GOOD_MEDIA_ID,
        "copyright": _GOOD_COPYRIGHT,
        "date_parution_prevue": _GOOD_DATE,
    }


def _make_form(app: Flask, data: dict | None = None) -> ArticleForm:
    """Instantiate `ArticleForm` against a fake POST payload.
    Encapsulates : test_request_context, ImmutableMultiDict wrapping,
    and choice-stubbing for every SelectField. RichSelectField's
    `_choices` callable pulls from `app.settings.vocabularies`, which
    is a DB-backed lookup — to keep these tests truly unit-scope and
    independent of any test fixture seeding, we replace each
    SelectField's `choices` attribute with a stable in-memory tuple.
    """
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = ArticleForm(payload)
        # Stub choices for every SelectField in the form. The
        # production view wires these from DB queries before
        # validation ; we provide a deterministic single-entry list
        # so SelectField pre-validation can run without a live DB.
        for name, good in (
            ("genre", _GOOD_GENRE),
            ("section", _GOOD_SECTION),
            ("topic", _GOOD_TOPIC),
            ("sector", _GOOD_SECTOR),
            ("media_id", _GOOD_MEDIA_ID),
            ("copyright", _GOOD_COPYRIGHT),
        ):
            form[name].choices = [
                (good, good),
                ("Creative Commons (CC-BY-SA-ND)", "Creative Commons (CC-BY-SA-ND)"),
            ]
        return form


class TestRequiredFields:
    """Pin every InputRequired the source declares. A future
    refactor that drops one of these would silently let half-built
    articles ship to the public newsroom."""

    def test_baseline_payload_validates(self, app: Flask):
        """Sanity : the minimal-good payload validates. Anchors the
        rest of the suite — if this breaks, every other test is
        suspect."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize(
        "field_name",
        [
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "date_parution_prevue",
        ],
    )
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        """Each declared-required field, when blanked, must surface
        an error on *that* field. Catches « accidentally removed
        InputRequired » regressions without enumerating per-field
        boilerplate."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize(
        "field_name",
        [
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "date_parution_prevue",
        ],
    )
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        """Same as blank, but the key isn't even present in the POST.
        WTForms treats missing-key and blank-value identically for
        InputRequired ; pin that contract so a future SelectField
        switch doesn't silently swallow missing keys."""
        payload = _baseline_payload()
        payload.pop(field_name)
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestOptionalFields:
    """Fields with no InputRequired must pass when empty. Pin the
    contract so a future « add InputRequired to chapo » doesn't
    silently reject every article submitted without a sub-headline."""

    @pytest.mark.parametrize(
        "field_name",
        ["chapo"],
    )
    def test_optional_blank_accepted(self, app: Flask, field_name: str):
        """The optional field, when empty, must NOT surface a
        per-field error. Whole-form validation may still pass — we
        only assert the field's own errors list is empty."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        form.validate()
        assert not form[field_name].errors

    def test_optional_blank_key_absent_accepted(self, app: Flask):
        """When `chapo` is simply absent from the POST (not even
        blank), the form must accept it. WTForms treats missing
        keys identically to empty values for fields without
        InputRequired."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Errors: {form.errors}"
        assert not form.chapo.errors

    def test_chapo_long_accepted(self, app: Flask):
        """No length cap on the sub-headline. Pin so a future
        « maxlength=200 » doesn't silently truncate long-form
        chapôs."""
        payload = _baseline_payload()
        payload["chapo"] = "x" * 5000
        form = _make_form(app, payload)
        assert form.validate(), f"Long chapo should validate, errors={form.errors}"


class TestSelectFieldChoices:
    """RichSelectField wraps a strict SelectField : values must be in
    `choices`. Pin so a future `validate_choice=False` regression
    that lets bogus values reach the DB is caught."""

    @pytest.mark.parametrize(
        "field_name",
        ["genre", "section", "topic", "sector"],
    )
    def test_bogus_choice_rejected(self, app: Flask, field_name: str):
        """A value that's not in the vocabulary must surface a per-
        field error. Catches both « JS client sent a stale value »
        and « vocab key was renamed » regressions."""
        payload = _baseline_payload()
        payload[field_name] = "totally-not-a-real-choice"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors

    def test_media_id_unknown_value_rejected(self, app: Flask):
        """The SimpleRichSelectField for `media_id` rejects any value
        not in `choices`. Our stub allows `"1"` only — a different
        id must fail."""
        payload = _baseline_payload()
        payload["media_id"] = "999-not-in-stub"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form.media_id.errors

    def test_copyright_must_be_known_value(self, app: Flask):
        """`copyright` has no InputRequired *but* the underlying
        SelectField still enforces « value must be a known choice ».
        Bogus values are rejected — pin so a future loosening
        doesn't silently store junk."""
        payload = _baseline_payload()
        payload["copyright"] = "bogus-mention"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form.copyright.errors

    def test_copyright_known_value_accepted(self, app: Flask):
        """Each canonical copyright mention must pass."""
        for mention in (
            "Tous droits réservés",
            "Creative Commons (CC-BY-SA-ND)",
        ):
            payload = _baseline_payload()
            payload["copyright"] = mention
            form = _make_form(app, payload)
            assert form.validate(), (
                f"Mention {mention!r} should pass, errors={form.errors}"
            )


class TestDateTimeParsing:
    """`DateTimeField` accepts three formats by default ; the
    publish-form template uses the HTML5 datetime-local format.
    Pin all three so a future widget swap doesn't silently break
    inbound requests from older clients."""

    @pytest.mark.parametrize(
        "value",
        [
            "2025-01-01 10:30:00",  # SQL-ish
            "2025-01-01T10:30:00",  # ISO-ish with seconds
            "2025-01-01T10:30",  # HTML5 datetime-local
        ],
    )
    def test_accepted_datetime_formats(self, app: Flask, value: str):
        """Each documented format must parse cleanly into a
        `datetime` and validate."""
        payload = _baseline_payload()
        payload["date_parution_prevue"] = value
        form = _make_form(app, payload)
        assert form.validate(), f"Format {value!r} should parse, errors={form.errors}"
        # All three formats normalize to the same datetime — pin so
        # a future « default-tz munging » regression is visible.
        assert form.date_parution_prevue.data is not None

    def test_garbage_datetime_rejected(self, app: Flask):
        """A non-parseable string must surface a per-field error."""
        payload = _baseline_payload()
        payload["date_parution_prevue"] = "not-a-date"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form.date_parution_prevue.errors

    def test_optional_datetime_absent_yields_none(self, app: Flask):
        """`date_publication_aip24` and `date_paiement` are optional.
        When the key is *absent* from the POST, the form must
        validate cleanly and `data` must be None — pin so a future
        sentinel default (e.g. `datetime.now()`) doesn't silently
        backdate every article."""
        payload = _baseline_payload()
        # Both keys intentionally absent.
        form = _make_form(app, payload)
        assert form.validate(), f"Errors: {form.errors}"
        assert form.date_publication_aip24.data is None
        assert form.date_paiement.data is None

    def test_optional_datetime_blank_string_rejected(self, app: Flask):
        """KNOWN-QUIRK : the source declares no `Optional()`
        validator on `date_publication_aip24` / `date_paiement`,
        so an empty *string* (vs. absent key) trips the format
        parser and produces a per-field error. Pin so a future
        « add Optional() validator » is a deliberate, visible
        change — not a silent semantic shift."""
        payload = _baseline_payload()
        payload["date_publication_aip24"] = ""
        form = _make_form(app, payload)
        form.validate()
        assert form.date_publication_aip24.errors


class TestFormShape:
    """Lock the public field surface. The form has a published
    `Meta.groups` mapping that the rendering layer iterates — if a
    field is renamed without updating Meta, the template silently
    drops the field. These tests pin the shape."""

    def test_field_names_are_stable(self, app: Flask):
        """Pin the exact set of fields so a rename is loud, not
        silent. The list mirrors the source declaration."""
        form = _make_form(app, {})
        expected = {
            "titre",
            "chapo",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "pays_zip_ville",
            "copyright",
            "date_parution_prevue",
            "date_publication_aip24",
            "date_paiement",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_only_reference_real_fields(self, app: Flask):
        """Every name listed in `Meta.groups[*].fields` must
        correspond to an actual form field. Catches « renamed field
        but forgot to update Meta » before the template breaks."""
        form = _make_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in ArticleForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared fields: {declared}"
                )

    def test_defaults_when_unfilled(self, app: Flask):
        """An empty POST must yield None / empty-string defaults
        across all fields. Pin so a future « class-level default »
        addition doesn't silently fill DB columns with surprises."""
        form = _make_form(app, {})
        # String-ish fields default to None or empty depending on
        # WTForms version ; both are falsy. Pin that they're falsy.
        for name in ("titre", "chapo", "contenu"):
            assert not form[name].data, (
                f"{name} should default falsy, got {form[name].data!r}"
            )
        # DateTime fields default to None.
        for name in (
            "date_parution_prevue",
            "date_publication_aip24",
            "date_paiement",
        ):
            assert form[name].data is None
