# Copyright (c) 2021-2026, Abilian SAS & TCA
#
# SPDX-License-Identifier: AGPL-3.0-only

"""Unit tests for `EventForm` validation in
`app.modules.wip.crud.cbvs._forms`.

WTForms validation runs in-process — no DB, no HTTP — so it lands
naturally in a_unit. The form is auto-generated (see the
"Autogenerated. DO NOT EDIT." banner in the source) and drives the
public event-submission CRUD flow ; pinning the validators here
catches three classes of silent regression :

1. **Tightening** : a future « add InputRequired to start_time »
   would break the legitimate « date TBD » draft-event workflow.
2. **Loosening** : a future accidental drop of `InputRequired` on
   `titre` / `contenu` / `sector` / `event_type` would let nameless
   or untagged events ship to the public-facing listings.
3. **Choice drift** : the `event_type` RichSelectField binds to the
   `events` vocab key (note the plural — easy to typo to `event`).
   Pin the binding so a global rename is caught.

The DateTimeField format (`%Y-%m-%dT%H:%M`) is the HTML5
`datetime-local` wire format — a regression to a different format
would silently lose the time portion of every event POST.

Note : the two `RichSelectField`s (`sector`, `event_type`) load
choices dynamically from `app.flask.forms.get_choices`, which reads
from the `tax_taxonomy` DB table. In the a_unit layer that table is
empty, so we override the field's `choices` list before validating
— a normal, mock-free assignment. That keeps these tests independent
of vocabulary seeding and pins the underlying contract (« value must
be a known choice ») deterministically.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from werkzeug.datastructures import ImmutableMultiDict

from app.modules.wip.crud.cbvs._forms import EventForm

if TYPE_CHECKING:
    from flask import Flask


# Stub values used to populate the two RichSelectField `choices`
# in `_make_form`. They have no semantic meaning — they only need
# to be stable enough to round-trip through SelectField's strict
# pre-validation.
_STUB_SECTOR = "STUB-SECTOR"
_STUB_EVENT_TYPE = "STUB-EVENT-TYPE"

_GOOD_TITRE = "Conférence test"
_GOOD_CONTENU = "Description de l'événement."
_GOOD_DATETIME = "2025-06-15T14:30"


def _baseline_payload() -> dict[str, str]:
    """Smallest dict that passes validation against the stubbed
    choices set in `_make_form`. Tests override individual keys to
    exercise specific branches without re-typing the full dict."""
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "sector": _STUB_SECTOR,
        "event_type": _STUB_EVENT_TYPE,
    }


def _make_form(app: Flask, data: dict | None = None) -> EventForm:
    """Instantiate `EventForm` against a fake POST payload.
    Encapsulates : test_request_context, ImmutableMultiDict wrapping,
    and stubbing of the two RichSelectField `choices` lists (the
    production code populates them from the taxonomy cache ; we
    override with a single-entry list so SelectField pre-validation
    can pass without a seeded DB)."""
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = EventForm(payload)
        form.sector.choices = [(_STUB_SECTOR, _STUB_SECTOR)]
        form.event_type.choices = [(_STUB_EVENT_TYPE, _STUB_EVENT_TYPE)]
        return form


class TestRequiredFields:
    """The four headline fields — `titre`, `contenu`, `sector`,
    `event_type` — are the minimum to publish an event. Drop any of
    them and the form must reject the POST. This pins the contract
    against an « accidentally removed InputRequired » regression."""

    def test_baseline_payload_validates(self, app: Flask):
        """Sanity : the minimal-good payload validates. Anchors the
        rest of the suite — if this breaks, every other test is
        suspect."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize(
        "field_name",
        ["titre", "contenu", "sector", "event_type"],
    )
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        """Each declared-required field, when blanked, must surface
        an error on *that* field. Catches « accidentally removed
        InputRequired » regressions without enumerating per-field
        boilerplate."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize(
        "field_name",
        ["titre", "contenu", "sector", "event_type"],
    )
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        """Same as blank, but the key isn't even present in the POST.
        WTForms treats missing-key and blank-value identically for
        InputRequired ; pin that contract so a future SelectField
        switch doesn't silently swallow missing keys."""
        payload = _baseline_payload()
        payload.pop(field_name)
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestOptionalFields:
    """Every field other than the four headline required ones is
    optional. Pin so a future « tighten optional → required » is
    visible in the test diff. Most importantly, `start_time` /
    `end_time` are optional by design (drafts often only know one
    anchor) — a future regression that adds InputRequired would
    silently break the « date TBD » draft workflow."""

    @pytest.mark.parametrize(
        "field_name",
        ["chapo", "address", "url", "start_time", "end_time"],
    )
    def test_optional_field_absent_passes(self, app: Flask, field_name: str):
        """A minimal payload omits every optional field ; the form
        must still validate. Parametrized so each optional field
        surfaces independently if it's accidentally tightened."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"
        assert not form[field_name].errors

    @pytest.mark.parametrize(
        "field_name",
        ["chapo", "address", "url", "start_time", "end_time"],
    )
    def test_optional_field_empty_string_passes(self, app: Flask, field_name: str):
        """Browsers POST empty strings for unfilled fields — the form
        must treat empty string identically to missing for optional
        fields. Catches a regression where Optional() is dropped (or
        swapped to DataRequired, which rejects empty strings)."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        assert form.validate(), (
            f"Empty {field_name} should validate, errors={form.errors}"
        )
        assert not form[field_name].errors

    def test_pays_zip_ville_optional(self, app: Flask):
        """`pays_zip_ville` is a `CountrySelectField` with
        `validate_choice=False` (the choices list is loaded
        client-side by the tom-select widget, not by the server).
        Pin so a future « add InputRequired » regression that
        breaks every event POST is visible."""
        form = _make_form(app, _baseline_payload())
        assert form.validate()
        assert not form.pays_zip_ville.errors


class TestSelectFieldChoices:
    """RichSelectField wraps a strict SelectField : values must be in
    `choices`. Pin so a future `validate_choice=False` regression
    that lets bogus values reach the DB is caught."""

    @pytest.mark.parametrize(
        "field_name",
        ["sector", "event_type"],
    )
    def test_bogus_choice_rejected(self, app: Flask, field_name: str):
        """A value that's not in the (stubbed) vocabulary must
        surface a per-field error. Catches both « JS client sent a
        stale value » and « vocab key was renamed » regressions."""
        payload = _baseline_payload()
        payload[field_name] = "totally-not-a-real-choice"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors

    def test_pays_zip_ville_accepts_any_value(self, app: Flask):
        """`pays_zip_ville` was deliberately configured with
        `validate_choice=False` because the country list is
        rendered client-side. Pin so a future « tighten validation »
        doesn't silently break the event POST path."""
        payload = _baseline_payload()
        payload["pays_zip_ville"] = "FR"  # not in the (empty) choices
        form = _make_form(app, payload)
        assert form.validate(), (
            f"pays_zip_ville must accept any string, errors={form.errors}"
        )

    def test_event_type_uses_events_vocabulary(self, app: Flask):
        """The `event_type` field binds to the `events` vocab key
        (note the plural — easy to typo to `event`). That naming
        subtlety is exactly the kind of thing a global rename
        misses ; pin it so we'd catch a silent regression."""
        form = _make_form(app, _baseline_payload())
        assert form.event_type.key == "events"

    def test_sector_uses_sector_vocabulary(self, app: Flask):
        """The `sector` field binds to the `sector` vocab key
        (singular, shared with the article/communique forms)."""
        form = _make_form(app, _baseline_payload())
        assert form.sector.key == "sector"


class TestDateTimeFields:
    """`start_time` and `end_time` are `DateTimeField`s with the
    HTML5 `datetime-local` format. Pin parsing so a future widget
    swap doesn't silently lose the time portion of every event."""

    def test_start_time_html5_format_accepted(self, app: Flask):
        """HTML5 `datetime-local` (`YYYY-MM-DDTHH:MM`) is what the
        event-form template emits. Pin so a future format swap is
        visible at the unit layer."""
        payload = _baseline_payload()
        payload["start_time"] = _GOOD_DATETIME
        form = _make_form(app, payload)
        assert form.validate(), f"HTML5 dt should parse, errors={form.errors}"
        assert form.start_time.data is not None

    def test_end_time_html5_format_accepted(self, app: Flask):
        payload = _baseline_payload()
        payload["end_time"] = _GOOD_DATETIME
        form = _make_form(app, payload)
        assert form.validate(), f"HTML5 dt should parse, errors={form.errors}"
        assert form.end_time.data is not None

    @pytest.mark.parametrize(
        "field_name",
        ["start_time", "end_time"],
    )
    def test_garbage_datetime_rejected(self, app: Flask, field_name: str):
        """Non-parseable strings must surface a per-field error on
        both datetime fields. Pin the failure mode so a silent
        widget regression that swallows parse errors is loud."""
        payload = _baseline_payload()
        payload[field_name] = "not-a-date"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors

    def test_end_before_start_accepted(self, app: Flask):
        """The form does NOT currently enforce `start <= end`.
        That's deliberate (drafts often have placeholder times) but
        easy to break with a well-intentioned `validate_*` override
        — pin the current behaviour so any such tightening is
        explicit, not accidental."""
        payload = _baseline_payload()
        payload["start_time"] = "2025-06-15T18:00"
        payload["end_time"] = "2025-06-15T09:00"
        form = _make_form(app, payload)
        assert form.validate(), (
            f"Inverted times should currently pass, errors={form.errors}"
        )


class TestFormShape:
    """Lock the public field surface. The form has a published
    `Meta.groups` mapping that the rendering layer iterates — if a
    field is renamed without updating Meta, the template silently
    drops the field. These tests pin the shape."""

    def test_field_names_are_stable(self, app: Flask):
        """Pin the exact set of fields so a rename is loud, not
        silent. The list mirrors the source declaration."""
        form = _make_form(app, {})
        expected = {
            "titre",
            "chapo",
            "contenu",
            "sector",
            "event_type",
            "address",
            "pays_zip_ville",
            "url",
            "start_time",
            "end_time",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_only_reference_real_fields(self, app: Flask):
        """Every name listed in `Meta.groups[*].fields` must
        correspond to an actual form field. Catches « renamed field
        but forgot to update Meta » before the template breaks."""
        form = _make_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in EventForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared fields: {declared}"
                )

    def test_meta_groups_expected_layout(self, app: Flask):
        """The four-group layout (headers / contenu / metadata /
        dates) is part of the rendered page contract. Pin it so a
        re-org is intentional and reviewed."""
        groups = EventForm.Meta.groups
        assert set(groups.keys()) == {"headers", "contenu", "metadata", "dates"}
        assert groups["dates"]["fields"] == ["start_time", "end_time"]
        # event_type leads the metadata group — it's the
        # most-prominent classifier on the rendered page.
        assert groups["metadata"]["fields"][0] == "event_type"

    def test_defaults_when_unfilled(self, app: Flask):
        """An empty POST must yield None / empty-string defaults
        across all fields. Pin so a future « class-level default »
        addition doesn't silently fill DB columns with surprises."""
        form = _make_form(app, {})
        for name in ("titre", "chapo", "contenu", "address", "url"):
            assert not form[name].data, (
                f"{name} should default falsy, got {form[name].data!r}"
            )
        for name in ("sector", "event_type"):
            assert form[name].data is None
        for name in ("start_time", "end_time"):
            assert form[name].data is None

    def test_country_field_dual_select_attributes(self, app: Flask):
        """`pays_zip_ville` is a `CountrySelectField`, which carries
        the second-input attributes (`name2`, `id2`, `label2`) used
        by the tom-select widget. Pin so a future template refactor
        that forgets to wire one of them is caught."""
        form = _make_form(app, {})
        assert form.pays_zip_ville.label.text == "Pays"
        assert form.pays_zip_ville.label2 == "Code postal et ville"
        assert form.pays_zip_ville.name2 == "pays_zip_ville_detail"
        assert form.pays_zip_ville.id2 == "pzv_detail"

    def test_select_render_widths(self, app: Flask):
        """The `render_kw['width']` values feed the renderer's grid
        — pin the widths so a future template refactor that drops
        the layout hint is visible. The widths mirror the source
        declaration : sector / event_type / address / url span 6 ;
        start_time / end_time span 3."""
        form = _make_form(app, {})
        assert form.sector.render_kw == {"width": 6}
        assert form.event_type.render_kw == {"width": 6}
        assert form.address.render_kw == {"width": 6}
        assert form.url.render_kw == {"width": 6}
        assert form.start_time.render_kw == {"width": 3}
        assert form.end_time.render_kw == {"width": 3}
