# Copyright (c) 2021-2026, Abilian SAS & TCA
#
# SPDX-License-Identifier: AGPL-3.0-only

"""Unit tests for `SujetForm` + `CommandeForm` validation in
`app.modules.wip.crud.cbvs._forms`.

`SujetForm` is what a journalist fills in to *pitch* a story idea to
a target media. `CommandeForm` is the symmetric form for a media
*commissioning* a story from a freelancer. Both share the same
taxonomy fields (genre / section / topic / sector / media_id) and a
country selector, but differ in their date workflow :

* `SujetForm` : `date_limite_validite` (offer expiry) +
  `date_parution_prevue` (planned publication).
* `CommandeForm` : adds `date_bouclage` (copy-deadline) and
  `date_paiement` (when the commissioner will pay).

WTForms validation runs in-process — no DB, no HTTP — so this file
lands cleanly in a_unit. The forms are auto-generated (see the
"Autogenerated. DO NOT EDIT." banner in the source) ; pinning the
validators here catches three classes of silent regression :

1. **Loosening** : an InputRequired silently dropped from one of the
   four taxonomy selectors, `media_id`, or any of the dates — letting
   under-specified pitches / commandes reach the workflow queues.
2. **Tightening on titre/contenu** : both forms intentionally leave
   `titre` + `contenu` *without* InputRequired (draft-friendly), so
   the journalist can save a stub before fleshing it out. A future
   « add InputRequired to titre » would silently block legitimate
   drafts ; pin the contract here.
3. **Shape drift** : a field renamed without updating `Meta.groups`,
   which the rendering layer iterates ; the template would silently
   drop the field from the rendered page. The two forms also differ
   in their date set : pin each so a CommandeForm date silently
   appearing in SujetForm (or vice-versa) is caught.

Why no mocks/patches : the forms are pure declarative WTForms
classes. We exercise them by constructing a real `Form` instance
against an `ImmutableMultiDict` payload (exactly what Flask does
behind the scenes) and asserting on `form.errors` / `form.data` —
tangible state outputs, not internal interactions.

`RichSelectField` / `SimpleRichSelectField` derive from `SelectField`
and pull their choice list from the taxonomy cache (DB-backed).
That cache is not seeded in a_unit fixtures, so we set each select
field's `choices` to a stable single-entry list before validating.
The production view wires real choices from a DB query before
calling `form.validate()` — our stub mirrors the same contract
without booting the taxonomy.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from werkzeug.datastructures import ImmutableMultiDict

from app.modules.wip.crud.cbvs._forms import CommandeForm, SujetForm

if TYPE_CHECKING:
    from flask import Flask


# Stub vocabulary values. They are intentionally non-semantic — we
# only need them to round-trip through SelectField pre-validation.
_STUB_GENRE = "STUB-GENRE"
_STUB_SECTION = "STUB-SECTION"
_STUB_TOPIC = "STUB-TOPIC"
_STUB_SECTOR = "STUB-SECTOR"
_STUB_MEDIA_ID = "42"

_GOOD_TITRE = "Un sujet de reportage"
_GOOD_CONTENU = "Brief du sujet à proposer."
_GOOD_DATETIME = "2025-03-15T10:30"


_SELECT_FIELDS: tuple[tuple[str, str], ...] = (
    ("genre", _STUB_GENRE),
    ("section", _STUB_SECTION),
    ("topic", _STUB_TOPIC),
    ("sector", _STUB_SECTOR),
    ("media_id", _STUB_MEDIA_ID),
)


def _stub_choices(form) -> None:
    """Populate each SelectField's `choices` with a single stable
    entry. The production view does this from a DB query right before
    validation ; we mirror the contract without a seeded taxonomy."""
    for name, good in _SELECT_FIELDS:
        form[name].choices = [(good, good)]


# ---------------------------------------------------------------------
# SujetForm
# ---------------------------------------------------------------------


_SUJET_DATE_FIELDS = ["date_limite_validite", "date_parution_prevue"]

_SUJET_REQUIRED_FIELDS = [
    "genre",
    "section",
    "topic",
    "sector",
    "media_id",
    "date_limite_validite",
    "date_parution_prevue",
]


def _sujet_baseline() -> dict[str, str]:
    """Smallest dict that validates against a stubbed-choice form."""
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "genre": _STUB_GENRE,
        "section": _STUB_SECTION,
        "topic": _STUB_TOPIC,
        "sector": _STUB_SECTOR,
        "media_id": _STUB_MEDIA_ID,
        "date_limite_validite": _GOOD_DATETIME,
        "date_parution_prevue": _GOOD_DATETIME,
    }


def _make_sujet_form(app: Flask, data: dict | None = None) -> SujetForm:
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = SujetForm(payload)
        _stub_choices(form)
        return form


class TestSujetFormRequiredFields:
    """Pin every InputRequired the source declares. A future refactor
    that drops one of these would silently let half-built sujets ship
    to the journalist's outbox."""

    def test_baseline_validates(self, app: Flask):
        """Sanity : the minimal-good payload validates. Anchors the
        rest of the suite — if this breaks, every other test is
        suspect."""
        form = _make_sujet_form(app, _sujet_baseline())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize("field_name", _SUJET_REQUIRED_FIELDS)
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        """Each declared-required field, when blanked, must surface
        an error on *that* field."""
        payload = _sujet_baseline()
        payload[field_name] = ""
        form = _make_sujet_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize("field_name", _SUJET_REQUIRED_FIELDS)
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        """Same as blank, but the key isn't even present in the POST.
        WTForms treats missing-key and blank-value identically for
        InputRequired ; pin that contract."""
        payload = _sujet_baseline()
        payload.pop(field_name)
        form = _make_sujet_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestSujetFormOptionalFields:
    """`titre` and `contenu` are intentionally OPTIONAL on `SujetForm`
    so a journalist can save a stub draft and fill it in later. Pin
    the contract so a future « add InputRequired to titre » doesn't
    silently block legitimate drafts."""

    @pytest.mark.parametrize("field_name", ["titre", "contenu"])
    def test_optional_field_empty_validates(self, app: Flask, field_name: str):
        payload = _sujet_baseline()
        payload[field_name] = ""
        form = _make_sujet_form(app, payload)
        assert form.validate(), (
            f"Empty {field_name} should validate (it's optional), errors={form.errors}"
        )

    @pytest.mark.parametrize("field_name", ["titre", "contenu"])
    def test_optional_field_missing_validates(self, app: Flask, field_name: str):
        payload = _sujet_baseline()
        payload.pop(field_name)
        form = _make_sujet_form(app, payload)
        assert form.validate(), (
            f"Missing {field_name} should validate (it's optional), "
            f"errors={form.errors}"
        )


class TestSujetFormSelectChoices:
    """SelectFields reject any value not present in `choices`. Pin so
    a future regression that relaxes `validate_choice` is caught."""

    @pytest.mark.parametrize(
        "field_name", ["genre", "section", "topic", "sector", "media_id"]
    )
    def test_bogus_choice_rejected(self, app: Flask, field_name: str):
        payload = _sujet_baseline()
        payload[field_name] = "totally-not-a-real-choice"
        form = _make_sujet_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestSujetFormDateTimeParsing:
    """`DateTimeField` accepts three default formats. The publish form
    uses HTML5 datetime-local ; pin all three per field so a widget
    swap can't silently drop a format on one field."""

    @pytest.mark.parametrize(
        "value",
        [
            "2025-03-15 10:30:00",
            "2025-03-15T10:30:00",
            "2025-03-15T10:30",
        ],
    )
    @pytest.mark.parametrize("field_name", _SUJET_DATE_FIELDS)
    def test_accepted_datetime_formats(self, app: Flask, field_name: str, value: str):
        payload = _sujet_baseline()
        payload[field_name] = value
        form = _make_sujet_form(app, payload)
        assert form.validate(), (
            f"{field_name}={value!r} should parse, errors={form.errors}"
        )
        assert form[field_name].data is not None

    @pytest.mark.parametrize("field_name", _SUJET_DATE_FIELDS)
    def test_garbage_datetime_rejected(self, app: Flask, field_name: str):
        payload = _sujet_baseline()
        payload[field_name] = "not-a-date"
        form = _make_sujet_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestSujetFormShape:
    """Lock the public field surface + Meta.groups consistency."""

    def test_field_names_are_stable(self, app: Flask):
        form = _make_sujet_form(app, {})
        expected = {
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "pays_zip_ville",
            "date_limite_validite",
            "date_parution_prevue",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_reference_real_fields(self, app: Flask):
        """Every name listed in `Meta.groups[*].fields` must exist as
        a real form field. Catches « renamed field but forgot Meta »
        before the template breaks at render time."""
        form = _make_sujet_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in SujetForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared={declared}"
                )

    def test_meta_groups_top_level_keys(self, app: Flask):
        assert set(SujetForm.Meta.groups.keys()) == {
            "headers",
            "metadata",
            "dates",
        }

    def test_dates_group_lists_both_sujet_dates(self, app: Flask):
        """`SujetForm` has exactly two date-fields (no bouclage, no
        paiement — those are CommandeForm only). Pin so a future
        cross-pollination is caught."""
        assert SujetForm.Meta.groups["dates"]["fields"] == [
            "date_limite_validite",
            "date_parution_prevue",
        ]

    def test_media_id_label_is_destinataire(self, app: Flask):
        """Bug #0132 : the `media_id` label was renamed from "Média"
        to "Média destinataire" to make clear this is *who receives*
        the pitch, not the author's media. Pin so a copy-paste from
        `CommandeForm` (which still says "Média") doesn't regress."""
        form = _make_sujet_form(app, {})
        assert form.media_id.label.text == "Média destinataire"


# ---------------------------------------------------------------------
# CommandeForm
# ---------------------------------------------------------------------


_COMMANDE_DATE_FIELDS = [
    "date_limite_validite",
    "date_bouclage",
    "date_parution_prevue",
    "date_paiement",
]

_COMMANDE_REQUIRED_FIELDS = [
    "genre",
    "section",
    "topic",
    "sector",
    "media_id",
    "date_limite_validite",
    "date_bouclage",
    "date_parution_prevue",
    "date_paiement",
]


def _commande_baseline() -> dict[str, str]:
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "genre": _STUB_GENRE,
        "section": _STUB_SECTION,
        "topic": _STUB_TOPIC,
        "sector": _STUB_SECTOR,
        "media_id": _STUB_MEDIA_ID,
        "date_limite_validite": _GOOD_DATETIME,
        "date_bouclage": _GOOD_DATETIME,
        "date_parution_prevue": _GOOD_DATETIME,
        "date_paiement": _GOOD_DATETIME,
    }


def _make_commande_form(app: Flask, data: dict | None = None) -> CommandeForm:
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = CommandeForm(payload)
        _stub_choices(form)
        return form


class TestCommandeFormRequiredFields:
    """Pin every InputRequired. CommandeForm has the same metadata
    contract as SujetForm *plus* two extra required dates
    (`date_bouclage`, `date_paiement`). Pinning both sets prevents a
    silent loosening in either form."""

    def test_baseline_validates(self, app: Flask):
        form = _make_commande_form(app, _commande_baseline())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize("field_name", _COMMANDE_REQUIRED_FIELDS)
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        payload = _commande_baseline()
        payload[field_name] = ""
        form = _make_commande_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize("field_name", _COMMANDE_REQUIRED_FIELDS)
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        payload = _commande_baseline()
        payload.pop(field_name)
        form = _make_commande_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestCommandeFormOptionalFields:
    """Same draft-friendly contract as SujetForm : `titre`/`contenu`
    can be empty, so a media can save a stub commande and fill it in
    later."""

    @pytest.mark.parametrize("field_name", ["titre", "contenu"])
    def test_optional_field_empty_validates(self, app: Flask, field_name: str):
        payload = _commande_baseline()
        payload[field_name] = ""
        form = _make_commande_form(app, payload)
        assert form.validate(), (
            f"Empty {field_name} should validate (it's optional), errors={form.errors}"
        )


class TestCommandeFormDateTimeParsing:
    """Pin the parse contract across the *four* CommandeForm dates,
    not just the two SujetForm shares. A regression on bouclage or
    paiement would break the commande workflow specifically."""

    @pytest.mark.parametrize("field_name", _COMMANDE_DATE_FIELDS)
    def test_iso_html5_format_accepted(self, app: Flask, field_name: str):
        payload = _commande_baseline()
        payload[field_name] = "2025-03-15T10:30"
        form = _make_commande_form(app, payload)
        assert form.validate(), (
            f"{field_name} should accept HTML5 datetime-local, errors={form.errors}"
        )
        assert form[field_name].data is not None

    @pytest.mark.parametrize("field_name", _COMMANDE_DATE_FIELDS)
    def test_garbage_datetime_rejected(self, app: Flask, field_name: str):
        payload = _commande_baseline()
        payload[field_name] = "not-a-date"
        form = _make_commande_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestCommandeFormShape:
    """Lock the public field surface + Meta.groups consistency. The
    four-date workflow is the defining difference between Commande
    and Sujet ; pinning the group's field-list catches a silent
    reorder, omission, or accidental cross-pollination."""

    def test_field_names_are_stable(self, app: Flask):
        form = _make_commande_form(app, {})
        expected = {
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "pays_zip_ville",
            "date_limite_validite",
            "date_bouclage",
            "date_parution_prevue",
            "date_paiement",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_reference_real_fields(self, app: Flask):
        form = _make_commande_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in CommandeForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared={declared}"
                )

    def test_meta_groups_top_level_keys(self, app: Flask):
        assert set(CommandeForm.Meta.groups.keys()) == {
            "headers",
            "metadata",
            "dates",
        }

    def test_dates_group_lists_all_four_commande_dates(self, app: Flask):
        """`CommandeForm` carries four date-fields in workflow order :
        validity → bouclage → parution → paiement. Pin the list to
        catch silent reorder / omission."""
        assert CommandeForm.Meta.groups["dates"]["fields"] == [
            "date_limite_validite",
            "date_bouclage",
            "date_parution_prevue",
            "date_paiement",
        ]

    def test_media_id_label_is_plain_media(self, app: Flask):
        """Counterpart to SujetForm's "Média destinataire" : on a
        commande, the media IS the author/commissioner, so the label
        stays plain "Média". Pin both labels to catch a silent
        copy-paste between the two forms."""
        form = _make_commande_form(app, {})
        assert form.media_id.label.text == "Média"


# ---------------------------------------------------------------------
# Cross-form consistency
# ---------------------------------------------------------------------


class TestSujetVsCommandeContrast:
    """The two forms share metadata + a country selector but diverge
    on the date workflow. Lock the diff so a future refactor can't
    blur the boundary."""

    def test_commande_has_extra_dates_not_in_sujet(self, app: Flask):
        sujet = _make_sujet_form(app, {})
        commande = _make_commande_form(app, {})
        sujet_fields = set(sujet._fields.keys())
        commande_fields = set(commande._fields.keys())
        # date_bouclage + date_paiement live only on CommandeForm.
        assert "date_bouclage" in commande_fields
        assert "date_paiement" in commande_fields
        assert "date_bouclage" not in sujet_fields
        assert "date_paiement" not in sujet_fields

    def test_shared_metadata_fields_identical(self, app: Flask):
        sujet = _make_sujet_form(app, {})
        commande = _make_commande_form(app, {})
        shared = {
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "pays_zip_ville",
            "date_limite_validite",
            "date_parution_prevue",
        }
        assert shared.issubset(set(sujet._fields.keys()))
        assert shared.issubset(set(commande._fields.keys()))
