# Copyright (c) 2021-2026, Abilian SAS & TCA
#
# SPDX-License-Identifier: AGPL-3.0-only

"""Unit tests for `AvisEnqueteForm` validation in
`app.modules.wip.crud.cbvs._forms`.

The « avis d'enquête » form (call-for-witnesses) drives a key
newsroom workflow : a journalist publishes a public request for
sources, with four mandatory dates (start, end, copy-deadline,
expected publication). Unlike `ArticleForm`, *every* date here is
required — silently loosening any of them would let an enquête ship
without a closing window, which the front-end relies on to filter
expired calls.

WTForms validation is in-process (no DB, no HTTP) so this file lands
in a_unit. The form is auto-generated (see "Autogenerated. DO NOT
EDIT." in the source) ; tests pin the validators so re-generation
that drops a constraint or renames a field is caught loudly.

Three classes of regression we want to prevent :

1. **Loosening** : an InputRequired silently dropped from one of
   `titre`, `contenu`, the four taxonomy fields, the four dates, or
   `media_id`, letting under-specified enquêtes reach the public
   listing.
2. **Choice drift** : a RichSelectField vocabulary key renamed
   without the form being re-generated, so the JS client's
   submission is silently rejected.
3. **Shape drift** : a field renamed without updating `Meta.groups`,
   which the rendering layer iterates ; the template would silently
   drop the field from the rendered page.

`RichSelectField` pulls choices from `app.flask.forms.get_choices`,
which is a DB-backed taxonomy lookup not seeded in a_unit fixtures.
To keep tests pure unit-scope and independent of taxonomy seeding,
we stub each SelectField's `choices` attribute with a stable in-
memory tuple — the production view wires the real choices from a DB
query before validation runs.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from werkzeug.datastructures import ImmutableMultiDict

from app.modules.wip.crud.cbvs._forms import AvisEnqueteForm

if TYPE_CHECKING:
    from flask import Flask


# Minimal-valid payload : every required field set to a known-good
# value. Tests override individual keys to exercise specific branches
# without retyping the full dict each time.
_GOOD_TITRE = "Recherche témoins"
_GOOD_CONTENU = "Brief de l'enquête"
_GOOD_GENRE = "Actualité"
_GOOD_SECTION = "Autres"
_GOOD_TOPIC = "INFO GÉNÉ / Politique"
_GOOD_SECTOR = "POLITIQUE / Autres"
_GOOD_MEDIA_ID = "1"
_GOOD_DATE_DEBUT = "2025-01-01T10:00"
_GOOD_DATE_FIN = "2025-01-31T18:00"
_GOOD_DATE_BOUCLAGE = "2025-02-05T12:00"
_GOOD_DATE_PARUTION = "2025-02-10T08:00"


def _baseline_payload() -> dict[str, str]:
    """Smallest dict that passes validation (with all SelectField
    `choices` stubbed via `_make_form`)."""
    return {
        "titre": _GOOD_TITRE,
        "contenu": _GOOD_CONTENU,
        "genre": _GOOD_GENRE,
        "section": _GOOD_SECTION,
        "topic": _GOOD_TOPIC,
        "sector": _GOOD_SECTOR,
        "media_id": _GOOD_MEDIA_ID,
        "date_debut_enquete": _GOOD_DATE_DEBUT,
        "date_fin_enquete": _GOOD_DATE_FIN,
        "date_bouclage": _GOOD_DATE_BOUCLAGE,
        "date_parution_prevue": _GOOD_DATE_PARUTION,
    }


def _make_form(app: Flask, data: dict | None = None) -> AvisEnqueteForm:
    """Instantiate `AvisEnqueteForm` against a fake POST payload.

    Encapsulates : test_request_context, ImmutableMultiDict wrapping,
    and choice-stubbing for every SelectField. RichSelectField's
    `_choices` callable pulls from `app.flask.forms.get_choices`, a
    DB-backed lookup — to keep these tests truly unit-scope and
    independent of taxonomy seeding, we replace each SelectField's
    `choices` with a stable in-memory tuple.
    """
    payload = ImmutableMultiDict(data or {})
    with app.test_request_context():
        form = AvisEnqueteForm(payload)
        # The production view wires these from DB queries before
        # validation ; we provide a deterministic single-entry list
        # so SelectField pre-validation can run without a live DB.
        for name, good in (
            ("genre", _GOOD_GENRE),
            ("section", _GOOD_SECTION),
            ("topic", _GOOD_TOPIC),
            ("sector", _GOOD_SECTOR),
            ("media_id", _GOOD_MEDIA_ID),
        ):
            form[name].choices = [(good, good)]
        return form


_ALL_REQUIRED_FIELDS = [
    "titre",
    "contenu",
    "genre",
    "section",
    "topic",
    "sector",
    "media_id",
    "date_debut_enquete",
    "date_fin_enquete",
    "date_bouclage",
    "date_parution_prevue",
]

_DATE_FIELDS = [
    "date_debut_enquete",
    "date_fin_enquete",
    "date_bouclage",
    "date_parution_prevue",
]

_SELECT_VOCAB_FIELDS = ["genre", "section", "topic", "sector"]


class TestRequiredFields:
    """Pin every InputRequired the source declares. A future
    refactor that drops one of these would silently let half-built
    enquêtes ship to the public listing — particularly dangerous for
    the four dates, which the listing relies on to filter expired
    calls."""

    def test_baseline_payload_validates(self, app: Flask):
        """Sanity : the minimal-good payload validates. Anchors the
        rest of the suite — if this breaks, every other test is
        suspect."""
        form = _make_form(app, _baseline_payload())
        assert form.validate(), f"Baseline should validate, errors={form.errors}"

    @pytest.mark.parametrize("field_name", _ALL_REQUIRED_FIELDS)
    def test_required_field_blank_fails(self, app: Flask, field_name: str):
        """Each declared-required field, when blanked, must surface
        an error on *that* field. Catches « accidentally removed
        InputRequired » regressions without per-field boilerplate."""
        payload = _baseline_payload()
        payload[field_name] = ""
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors, (
            f"Expected error on {field_name}, got errors={form.errors}"
        )

    @pytest.mark.parametrize("field_name", _ALL_REQUIRED_FIELDS)
    def test_required_field_missing_fails(self, app: Flask, field_name: str):
        """Same as blank, but the key isn't even present in the POST.
        WTForms treats missing-key and blank-value identically for
        InputRequired ; pin that contract so a future SelectField
        switch doesn't silently swallow missing keys."""
        payload = _baseline_payload()
        payload.pop(field_name)
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestSelectFieldChoices:
    """RichSelectField wraps a strict SelectField : values must be in
    `choices`. Pin so a future `validate_choice=False` regression
    that lets bogus values reach the DB is caught."""

    @pytest.mark.parametrize("field_name", _SELECT_VOCAB_FIELDS)
    def test_bogus_choice_rejected(self, app: Flask, field_name: str):
        """A value not in the vocabulary must surface a per-field
        error. Catches both « JS client sent a stale value » and
        « vocab key was renamed » regressions."""
        payload = _baseline_payload()
        payload[field_name] = "totally-not-a-real-choice"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors

    def test_media_id_unknown_value_rejected(self, app: Flask):
        """`media_id` uses SimpleRichSelectField, which rejects any
        value not in `choices`. Our stub allows `"1"` only — a
        different id must fail."""
        payload = _baseline_payload()
        payload["media_id"] = "999-not-in-stub"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form.media_id.errors


class TestDateTimeParsing:
    """`DateTimeField` accepts three formats by default ; the
    publish-form template uses the HTML5 datetime-local format.
    Pin all three for each date so a future widget swap doesn't
    silently break inbound requests."""

    @pytest.mark.parametrize(
        "value",
        [
            "2025-01-01 10:30:00",  # SQL-ish
            "2025-01-01T10:30:00",  # ISO-ish with seconds
            "2025-01-01T10:30",  # HTML5 datetime-local
        ],
    )
    @pytest.mark.parametrize("field_name", _DATE_FIELDS)
    def test_accepted_datetime_formats(self, app: Flask, field_name: str, value: str):
        """Each documented format must parse cleanly into a
        `datetime` and validate the form. Pinning the cross-product
        ensures no single date field silently drops a format."""
        payload = _baseline_payload()
        payload[field_name] = value
        form = _make_form(app, payload)
        assert form.validate(), (
            f"{field_name}={value!r} should parse, errors={form.errors}"
        )
        assert form[field_name].data is not None

    @pytest.mark.parametrize("field_name", _DATE_FIELDS)
    def test_garbage_datetime_rejected(self, app: Flask, field_name: str):
        """A non-parseable string must surface a per-field error on
        every date — pinning all four prevents one being silently
        loosened to a string column."""
        payload = _baseline_payload()
        payload[field_name] = "not-a-date"
        form = _make_form(app, payload)
        assert not form.validate()
        assert form[field_name].errors


class TestFormShape:
    """Lock the public field surface. The form publishes a
    `Meta.groups` mapping that the rendering layer iterates ; if a
    field is renamed without updating Meta, the template silently
    drops it. These tests pin the shape and the Meta consistency."""

    def test_field_names_are_stable(self, app: Flask):
        """Pin the exact set of fields so a rename is loud, not
        silent. The list mirrors the source declaration."""
        form = _make_form(app, {})
        expected = {
            "titre",
            "contenu",
            "genre",
            "section",
            "topic",
            "sector",
            "media_id",
            "pays_zip_ville",
            "date_debut_enquete",
            "date_fin_enquete",
            "date_bouclage",
            "date_parution_prevue",
        }
        assert set(form._fields.keys()) == expected

    def test_meta_groups_only_reference_real_fields(self, app: Flask):
        """Every name listed in `Meta.groups[*].fields` must
        correspond to an actual form field. Catches « renamed field
        but forgot to update Meta » before the template breaks at
        render time."""
        form = _make_form(app, {})
        declared = set(form._fields.keys())
        for group_name, group in AvisEnqueteForm.Meta.groups.items():
            for field_name in group["fields"]:
                assert field_name in declared, (
                    f"Group {group_name!r} references unknown field "
                    f"{field_name!r} ; declared fields: {declared}"
                )

    def test_meta_groups_cover_expected_buckets(self, app: Flask):
        """Pin the top-level group names. The rendering layer
        iterates them in declaration order to build sections of the
        publish page ; a silent rename would hide a section."""
        assert set(AvisEnqueteForm.Meta.groups.keys()) == {
            "headers",
            "metadata",
            "dates",
        }

    def test_dates_group_lists_all_four_dates(self, app: Flask):
        """The four dates form a coherent workflow (start → end →
        bouclage → parution). All four must be in the `dates` group
        so the publish page renders them together — pinning the
        group's field list catches a silent reorder or omission."""
        assert AvisEnqueteForm.Meta.groups["dates"]["fields"] == [
            "date_debut_enquete",
            "date_fin_enquete",
            "date_bouclage",
            "date_parution_prevue",
        ]

    def test_defaults_when_unfilled(self, app: Flask):
        """An empty POST must yield None / empty-string defaults
        across all fields. Pin so a future « class-level default »
        addition doesn't silently fill DB columns with surprises."""
        form = _make_form(app, {})
        for name in ("titre", "contenu"):
            assert not form[name].data, (
                f"{name} should default falsy, got {form[name].data!r}"
            )
        for name in _DATE_FIELDS:
            assert form[name].data is None
