# Copyright (c) 2024, Abilian SAS & TCA
#
# Autogenerated. DO NOT EDIT.
#
from __future__ import annotations

from wtforms import Form, validators
from wtforms.fields.choices import SelectField
from wtforms.fields.simple import StringField, TextAreaField

from app.flask.lib.wtforms.fields import DateTimeField, RichSelectField, RichTextField


class ArticleForm(Form):

    # Group: headers
    titre = StringField("Titre", validators=[validators.InputRequired()])
    chapo = TextAreaField("Chapô")

    # Group: contenu
    contenu = RichTextField("Contenu", validators=[validators.InputRequired()])

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Thématique",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    # Group: copyright
    copyright = RichSelectField(
        "Mention du copyright", key="copyright-mention", render_kw={"width": 3}
    )

    # Group: dates
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue", render_kw={"width": 3}
    )
    date_publication_aip24 = DateTimeField(
        "Date/heure de publication sur AIP24", render_kw={"width": 3}
    )
    date_paiement = DateTimeField("Date/heure de paiement", render_kw={"width": 3})

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "chapo"]},
            "contenu": {"label": "Contenu de l'article", "fields": ["contenu"]},
            "metadata": {
                "label": "Métadonnées de l'article",
                "fields": ["genre", "section", "topic", "sector"],
            },
            "copyright": {"label": "Copyright de l'article", "fields": ["copyright"]},
            "dates": {
                "label": "Dates-clés de l'article",
                "fields": [
                    "date_parution_prevue",
                    "date_publication_aip24",
                    "date_paiement",
                ],
            },
        }


class AvisEnqueteForm(Form):

    # Group: headers
    titre = StringField("Titre", validators=[validators.InputRequired()])
    contenu = TextAreaField("Brief", validators=[validators.InputRequired()])

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Thématique",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    # Group: dates
    date_debut_enquete = DateTimeField(
        "Date/heure de début",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_fin_enquete = DateTimeField(
        "Date/heure de fin",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_bouclage = DateTimeField(
        "Date/heure de bouclage",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": ["genre", "section", "topic", "sector"],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": [
                    "date_debut_enquete",
                    "date_fin_enquete",
                    "date_bouclage",
                    "date_parution_prevue",
                ],
            },
        }


class SujetForm(Form):

    # Group: headers
    titre = StringField("Titre")
    contenu = TextAreaField("Brief")
    # fixme: remove media for now
    # media = SelectField("Média", render_kw={"width": 3})

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Thématique",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    # Group: dates
    date_limite_validite = DateTimeField("Date/heure de début", render_kw={"width": 3})
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue", render_kw={"width": 3}
    )

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            # fixme: remove "media" field for now
            # "headers": {"label": "", "fields": ["titre", "contenu", "media"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": ["genre", "section", "topic", "sector"],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": ["date_limite_validite", "date_parution_prevue"],
            },
        }


class CommandeForm(Form):

    # Group: headers
    titre = StringField("Titre")
    contenu = TextAreaField("Brief")

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Thématique",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    # Group: dates
    date_limite_validite = DateTimeField("Date/heure de début", render_kw={"width": 3})
    date_bouclage = DateTimeField("Date/heure de bouclage", render_kw={"width": 3})
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue", render_kw={"width": 3}
    )
    date_paiement = DateTimeField("Date/heure de paiement", render_kw={"width": 3})

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": ["genre", "section", "topic", "sector"],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": [
                    "date_limite_validite",
                    "date_bouclage",
                    "date_parution_prevue",
                    "date_paiement",
                ],
            },
        }
