# Copyright (c) 2024, Abilian SAS & TCA
#
# Autogenerated. DO NOT EDIT.
#
from __future__ import annotations

from wtforms import Form, validators
from wtforms.fields.choices import SelectField, SelectMultipleField
from wtforms.fields.simple import StringField, TextAreaField

from app.enums import MODE_LABELS, PRICING_LABELS, EventMode, EventPricing
from app.flask.lib.wtforms.fields import (
    DateTimeField,
    OptionalIdField,
    PriceField,
    RichSelectField,
    RichTextField,
    SimpleRichSelectField,
)
from app.modules.kyc.dynform import CountrySelectField


def country_and_city_field() -> CountrySelectField:
    """The country + postcode/city pair, declared identically by every
    WIP form.

    Six byte-identical thirteen-line blocks said this before.

    Called in a form class body, so what it actually hands back is a
    fresh `UnboundField` — WTForms' `Field.__new__` swaps it in, and
    each call gets its own creation counter, which is what keeps the six
    forms' field order intact. The annotation says `CountrySelectField`
    because that is what the constructor is statically; no annotation
    expresses the metaclass swap.
    """
    return CountrySelectField(
        name="pays_zip_ville",
        name2="pays_zip_ville_detail",
        label="Pays",
        id="pzv",
        id2="pzv_detail",
        label2="Code postal et ville",
        choices=[],
        # validators=validators_list,
        validate_choice=False,
        # render_kw=render_kw,
        readonly=0,
    )


class ArticleForm(Form):
    # Group: headers
    titre = StringField("Titre", validators=[validators.InputRequired()])
    chapo = TextAreaField("Chapô")

    # Group: contenu
    contenu = RichTextField("Contenu", validators=[validators.InputRequired()])

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Type d'info",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    media_id = SimpleRichSelectField(
        "Média",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    pays_zip_ville = country_and_city_field()

    # Group: copyright
    copyright = RichSelectField(
        "Mention du copyright", key="copyright-mention", render_kw={"width": 3}
    )

    # Group: dates
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_publication_aip24 = DateTimeField(
        "Date/heure de publication sur AiPRESS24", render_kw={"width": 3}
    )
    date_paiement = DateTimeField("Date/heure de paiement", render_kw={"width": 3})

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "chapo"]},
            "contenu": {"label": "Contenu de l'article", "fields": ["contenu"]},
            "metadata": {
                "label": "Métadonnées de l'article",
                "fields": [
                    "genre",
                    "section",
                    "topic",
                    "sector",
                    "media_id",
                    "pays_zip_ville",
                ],
            },
            "copyright": {"label": "Copyright de l'article", "fields": ["copyright"]},
            "dates": {
                "label": "Dates-clés de l'article",
                "fields": [
                    "date_parution_prevue",
                    "date_publication_aip24",
                ],
            },
        }


class AvisEnqueteForm(Form):
    # Group: headers
    titre = StringField("Titre", validators=[validators.InputRequired()])
    contenu = TextAreaField("Brief", validators=[validators.InputRequired()])

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Type d'info",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    media_id = SimpleRichSelectField(
        "Média",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    pays_zip_ville = country_and_city_field()

    # Group: dates
    date_debut_enquete = DateTimeField(
        "Date/heure de début",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_fin_enquete = DateTimeField(
        "Date/heure de fin",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_bouclage = DateTimeField(
        "Date/heure de bouclage",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": [
                    "genre",
                    "section",
                    "topic",
                    "sector",
                    "media_id",
                    "pays_zip_ville",
                ],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": [
                    "date_debut_enquete",
                    "date_fin_enquete",
                    "date_bouclage",
                    "date_parution_prevue",
                ],
            },
        }


class SujetForm(Form):
    # Group: headers
    titre = StringField("Titre")
    contenu = TextAreaField("Brief")
    # fixme: remove media for now
    # media = SelectField("Média", render_kw={"width": 3})

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Type d'info",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    # Bug #0132: label renamed from "Média" to "Média destinataire" so
    # the form makes clear this is *who receives* the proposal, not the
    # author's media.
    media_id = SimpleRichSelectField(
        "Média destinataire",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    pays_zip_ville = country_and_city_field()

    # Group: dates
    date_limite_validite = DateTimeField(
        "Date/heure de début",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": [
                    "genre",
                    "section",
                    "topic",
                    "sector",
                    "media_id",
                    "pays_zip_ville",
                ],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": ["date_limite_validite", "date_parution_prevue"],
            },
        }


class CommandeForm(Form):
    publisher_label_prefix = "Commande passée par"

    # Group: headers
    titre = StringField("Titre")
    contenu = TextAreaField("Brief")

    # Group: metadata
    genre = RichSelectField(
        "Genre",
        key="genre",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Type d'info",
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    sector = RichSelectField(
        "Secteur",
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    media_id = SimpleRichSelectField(
        "Commande adressée à",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    pays_zip_ville = country_and_city_field()

    # Group: dates
    date_limite_validite = DateTimeField(
        "Date/heure de début",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_bouclage = DateTimeField(
        "Date/heure de bouclage",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_parution_prevue = DateTimeField(
        "Date/heure de parution prévue",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    date_paiement = DateTimeField(
        "Date/heure de paiement",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    class Meta:
        groups = {
            "headers": {"label": "", "fields": ["titre", "contenu"]},
            "metadata": {
                "label": "Métadonnées",
                "fields": [
                    "genre",
                    "section",
                    "topic",
                    "sector",
                    "media_id",
                    "pays_zip_ville",
                ],
            },
            "dates": {
                "label": "Dates-clés",
                "fields": [
                    "date_limite_validite",
                    "date_bouclage",
                    "date_parution_prevue",
                    "date_paiement",
                ],
            },
        }


# --------------------------------------------------------------------------


class CommuniqueForm(Form):
    # --- Groupe: En-têtes ---
    titre = StringField("Titre du communiqué", validators=[validators.InputRequired()])

    # --- Groupe: Contenu ---
    chapo = TextAreaField("Chapô")
    contenu = RichTextField(
        "Contenu principal", validators=[validators.InputRequired()]
    )

    # --- Groupe: Métadonnées ---
    sector = RichSelectField(
        "Secteur",  # (NEWS-Secteur)
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )
    section = RichSelectField(
        "Rubrique",  # (NEWS-Rubrique)
        key="section",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )
    topic = RichSelectField(
        "Type d'info",  # (NEWS-Type d'info)
        key="topic",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    genre = RichSelectField(
        "Genre",  # (COM-Genre) -> TODO
        key="genre-com",
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    pays_zip_ville = country_and_city_field()

    # --- Groupe: Dates ---
    embargoed_until = DateTimeField(
        "Date/heure d'embargo (parution prévue)",
        render_kw={"width": 3},
        validators=[validators.Optional()],
        format="%Y-%m-%dT%H:%M",
    )
    published_at = DateTimeField(
        "Date/heure de publication effective",
        render_kw={"width": 3},
        # validators=[validators.Optional()],
        format="%Y-%m-%dT%H:%M",
    )

    class Meta:
        groups = {
            "headers": {
                "label": "En-têtes du communiqué",
                "fields": ["titre", "chapo"],
            },
            "contenu": {
                "label": "Contenu du communiqué",
                "fields": ["contenu"],
            },
            "metadata": {
                "label": "Métadonnées du communiqué",
                "fields": [
                    "genre",
                    "section",
                    "topic",
                    "sector",
                    "pays_zip_ville",
                ],
            },
            "dates": {
                "label": "Dates-clés du communiqué",
                "fields": [
                    "embargoed_until",
                    "published_at",
                ],
            },
        }


# --------------------------------------------------------------------------


class EventForm(Form):
    # --- Groupe: En-têtes ---
    titre = StringField("Titre de l'événement", validators=[validators.InputRequired()])

    # --- Groupe: Contenu ---
    chapo = TextAreaField("Chapô")
    contenu = RichTextField(
        "Contenu principal", validators=[validators.InputRequired()]
    )

    # --- Groupe: Métadonnées ---
    sector = RichSelectField(
        "Secteur",  # (NEWS-Secteur)
        key="sector",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    event_type = RichSelectField(
        "Type d'événement",  # EVENTS
        key="events",
        render_kw={"width": 6},
        validators=[validators.InputRequired()],
    )

    # FIL-01/FIL-02 : mêmes noms et mêmes vocabulaires que WIRE, mais
    # facultatifs — les rendre obligatoires invaliderait les événements
    # déjà saisis. Les libellés suivent l'ontologie : `sections` est
    # peuplé depuis la feuille « Rubriques », `topics` depuis « Type
    # d'info ». La barre de filtres de WIRE intervertit les deux ; on
    # ne propage pas l'erreur ici.
    section = RichSelectField(
        "Rubrique",
        key="section",
        render_kw={"width": 3},
        validators=[validators.Optional()],
    )
    topic = RichSelectField(
        "Type d'info",
        key="topic",
        render_kw={"width": 3},
        validators=[validators.Optional()],
    )

    # Décision `M1` — à qui l'événement s'adresse. Des métadonnées, au
    # même titre que la rubrique : elles ne restreignent la visibilité de
    # personne. `SelectMultipleField` natif et non `RichSelectField` :
    # celui-ci ne rend qu'une valeur, et résout ses options dans la table
    # des taxonomies, alors que les fonctions sont **calculées** — les
    # familles de quatre ontologies (voir `events/taxonomies.py`). Les
    # options sont posées par `_make_media_choices`.
    competences = SelectMultipleField(
        "Compétences visées",
        render_kw={"width": 6},
        validators=[validators.Optional()],
    )
    fonctions = SelectMultipleField(
        "Fonctions visées",
        render_kw={"width": 6},
        validators=[validators.Optional()],
    )

    # MOD-01 — le mode décide de ce qui est obligatoire pour publier.
    # Un `SelectField` aux choix déclarés en dur, et non un
    # `RichSelectField` : celui-ci résout ses options dans la table des
    # taxonomies, ce que MOD-06 écarte explicitement pour ce champ.
    #
    # Les choix portent le **nom** du membre et non sa valeur : c'est ce
    # que `sa.Enum` stocke en base, et écrire la forme minuscule ferait
    # lever `LookupError` à l'ORM en relecture.
    mode = SelectField(
        "Format de l'événement",
        choices=[(m.name, MODE_LABELS[m].capitalize()) for m in EventMode],
        default=EventMode.ON_SITE.name,
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    platform = StringField(
        "Plateforme (pour les événements en distanciel ou hybrides)",
        render_kw={"width": 3},
        validators=[validators.Optional()],
    )

    address = TextAreaField(
        "Adresse de l'événement (pour les événements en présentiel ou hybrides)",
        render_kw={"width": 6},
        validators=[validators.Optional()],
    )

    pays_zip_ville = country_and_city_field()

    url = StringField(
        "URL de l'événement (pour les événements en ligne ou hybrides)",
        render_kw={"width": 6},
        validators=[validators.Optional()],
    )

    # MOD-02 — réservé aux personnes accréditées : il n'apparaît ni sur
    # la liste, ni pour un visiteur, ni dans l'index de recherche. Le
    # rappel de la veille est le seul endroit où un accrédité le
    # reçoit sans revenir sur le site (NOT-13).
    access_details = TextAreaField(
        "Modalités d'accès (obligatoires pour une conférence téléphonique)",
        render_kw={"width": 6},
        validators=[validators.Optional()],
    )

    # PRX-01 — comme `mode`, un `SelectField` aux choix déclarés en dur,
    # portant le **nom** du membre : c'est ce que `sa.Enum` stocke.
    pricing = SelectField(
        "Tarif",
        choices=[(p.name, PRICING_LABELS[p]) for p in EventPricing],
        default=EventPricing.FREE_FOR_ALL.name,
        render_kw={"width": 3},
        validators=[validators.InputRequired()],
    )

    # PRX-02 — saisi en **euros**, stocké en centimes. La conversion se
    # fait dans le formulaire (`process_formdata`), jamais dans le
    # modèle : la base ne connaît que des entiers.
    #
    # Le champ n'est pas masqué en Alpine comme la spécification le
    # suggère : le moteur de rendu ne thread aucun attribut arbitraire
    # jusqu'au gabarit, seulement `class`. La condition est donc dans
    # le libellé, comme pour l'adresse et l'URL — et la vraie garde est
    # côté serveur, dans `publish()`.
    # ORG-01 — l'organisateur, quand ce n'est pas l'éditeur. Un
    # sélecteur d'organisations, et un texte libre pour un organisateur
    # absent d'AiPRESS24.
    #
    # `validate_choice=False` : les options sont injectées par la vue
    # (`_make_media_choices`), et une pré-validation contre une liste
    # encore vide refuserait toute saisie. C'est la clé étrangère qui
    # tient la cohérence, comme pour le pays.
    organiser_id = OptionalIdField(
        "Organisateur (s'il est inscrit sur AiPRESS24)",
        choices=[],
        validate_choice=False,
        render_kw={"width": 3},
        validators=[validators.Optional()],
    )
    organiser_name = StringField(
        "Organisateur (s'il est absent d'AiPRESS24)",
        render_kw={"width": 3},
        validators=[validators.Optional()],
    )

    price = PriceField(
        "Prix en euros (obligatoire si le tarif n'est pas « gratuit »)",
        render_kw={"width": 3},
        validators=[validators.Optional(), validators.NumberRange(min=0.01)],
    )

    # --- Groupe: Dates ---
    start_time = DateTimeField(
        "Date/heure de début de l'événement",
        render_kw={"width": 3},
        validators=[validators.Optional()],
        format="%Y-%m-%dT%H:%M",
    )
    end_time = DateTimeField(
        "Date/heure de fin",
        render_kw={"width": 3},
        validators=[validators.Optional()],
        format="%Y-%m-%dT%H:%M",
    )

    class Meta:
        groups = {
            "headers": {
                "label": "En-têtes de l'événement",
                "fields": ["titre", "chapo"],
            },
            "contenu": {
                "label": "Contenu de l'événement",
                "fields": ["contenu"],
            },
            "metadata": {
                "label": "Métadonnées de l'événement",
                "fields": [
                    "event_type",
                    "sector",
                    "section",
                    "topic",
                    "competences",
                    "fonctions",
                    "mode",
                    "platform",
                    "address",
                    "pays_zip_ville",
                    "url",
                    "access_details",
                    "pricing",
                    "price",
                    "organiser_id",
                    "organiser_name",
                ],
            },
            "dates": {
                "label": "Dates de l'événement",
                "fields": [
                    "start_time",
                    "end_time",
                ],
            },
        }
